/// Banque d'items du sous-test Vocabulaire — de (GÉNÉRÉ par IA, vérifié). 5 bandes de fréquence. NE PAS éditer à la main.
library;

import 'vocabulary_generator.dart';

List<List<VocabularyItem>> buildGermanVocabularyBanks() {
  return [
    // veryHigh (15 items)
    [
      VocabularyItem(word: 'Haus', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Gebäude, das Menschen als Wohnung und Schutz vor Wetter dient.', 'Bauwerk mit Wänden und Dach, in dem eine oder mehrere Familien wohnen.', 'Errichtetes Bauwerk, das jemandem als fester Wohnsitz dient.', 'Feststehendes Gebäude, in dem man wohnt, schläft und lebt.'], onePointAnswers: ['Der Ort, an dem man wohnt.', 'Eine feste Bleibe.', 'Die Wohnung von jemandem.', 'Wo man schläft und isst.', 'Ein Gebäude zum Wohnen.', 'Etwas mit Dach und Türen.'], thetaValue: -2.0),
      VocabularyItem(word: 'Wasser', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Durchsichtige, geruchlose Flüssigkeit, die man trinkt und zum Waschen benutzt.', 'Farblose Flüssigkeit, aus der Flüsse, Seen und Meere bestehen.', 'Klare Flüssigkeit ohne Eigengeschmack, die alle Lebewesen zum Leben brauchen.', 'Flüssigkeit, die als Regen fällt und in Bächen und Quellen fließt.'], onePointAnswers: ['Das, was man trinkt, wenn man Durst hat.', 'Was aus dem Hahn fließt.', 'Was im Meer und im Fluss ist.', 'Eine klare Flüssigkeit.', 'Regen besteht daraus.', 'Man wäscht sich damit.'], thetaValue: -2.0),
      VocabularyItem(word: 'essen', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Feste Nahrung zu sich nehmen, indem man sie kaut und herunterschluckt.', 'Speisen in den Mund nehmen, zerkleinern und verschlucken.', 'Nahrung aufnehmen, um satt zu werden und Kraft zu bekommen.', 'Etwas Festes verzehren, um den Hunger zu stillen.'], onePointAnswers: ['Etwas in den Mund nehmen und kauen.', 'Eine Mahlzeit zu sich nehmen.', 'Den Hunger stillen.', 'Frühstücken oder zu Abend speisen.', 'Nahrung verzehren.', 'Was man am Tisch macht, wenn man Hunger hat.'], thetaValue: -2.0),
      VocabularyItem(word: 'groß', frequency: WordFrequency.veryHigh, twoPointAnswers: ['In Höhe, Länge oder Umfang über dem Üblichen liegend.', 'So beschaffen, dass es viel Raum einnimmt oder weit ausgedehnt ist.', 'Von beträchtlicher Ausdehnung, Menge oder Stärke.', 'Über das gewöhnliche Maß hinausgehend, was die Abmessungen betrifft.'], onePointAnswers: ['Nicht klein.', 'Von beachtlicher Ausdehnung.', 'Hoch oder weit.', 'Wie ein Elefant verglichen mit einer Maus.', 'Umfangreich oder ausgedehnt.', 'Mit viel Platz oder Höhe.'], thetaValue: -2.0),
      VocabularyItem(word: 'Zeit', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Das stetige Ablaufen von Augenblicken, das man in Stunden und Tagen misst.', 'Der messbare Verlauf von Vergangenheit, Gegenwart und Zukunft.', 'Abschnitt oder Spanne, in der etwas geschieht oder dauert.', 'Das fortlaufende Vergehen, an dem sich Uhren und Kalender orientieren.'], onePointAnswers: ['Was die Uhr anzeigt.', 'Stunden, Minuten und Tage.', 'Was vergeht, während man wartet.', 'Eine Dauer oder Spanne.', 'Das, wovon man manchmal zu wenig hat.', 'Vergangenheit, Gegenwart und Zukunft.'], thetaValue: -2.0),
      VocabularyItem(word: 'gehen', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Sich auf den Füßen schrittweise von einem Ort zum anderen bewegen.', 'Sich zu Fuß fortbewegen, indem man einen Fuß vor den anderen setzt.', 'Sich aus eigener Kraft schreitend von einer Stelle wegbewegen.', 'Einen Ort verlassen oder zu Fuß einen anderen aufsuchen.'], onePointAnswers: ['Sich zu Fuß bewegen.', 'Einen Schritt nach dem anderen machen.', 'Sich schreitend fortbewegen.', 'Von einem Ort zum anderen kommen.', 'Einen Raum verlassen.', 'Spazieren.'], thetaValue: -2.0),
      VocabularyItem(word: 'Kind', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Junger Mensch, der noch nicht erwachsen ist.', 'Person im Lebensabschnitt zwischen Geburt und Erwachsensein.', 'Sohn oder Tochter im Verhältnis zu den Eltern.', 'Noch nicht erwachsener Mensch, der heranwächst und lernt.'], onePointAnswers: ['Ein kleiner Mensch.', 'Noch kein Erwachsener.', 'Sohn oder Tochter.', 'Jemand, der noch zur Schule geht.', 'Ein Mädchen oder ein Junge.', 'Der Nachwuchs der Eltern.'], thetaValue: -2.0),
      VocabularyItem(word: 'Tag', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Zeitraum von vierundzwanzig Stunden zwischen Mitternacht und Mitternacht.', 'Die helle Zeit zwischen Sonnenaufgang und Sonnenuntergang.', 'Einzelner Abschnitt des Kalenders, der einer Drehung der Erde entspricht.', 'Zeitspanne, in der es draußen hell ist und die Sonne scheint.'], onePointAnswers: ['Vierundzwanzig Stunden.', 'Die Zeit, wenn es hell ist.', 'Das Gegenteil von Nacht.', 'Was im Kalender mit einer Zahl gezählt wird.', 'Von morgens bis abends.', 'Eine Einheit der Woche.'], thetaValue: -2.0),
      VocabularyItem(word: 'sehen', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Mit den Augen etwas wahrnehmen oder erkennen.', 'Durch das Augenlicht Gegenstände und Vorgänge bemerken.', 'Etwas mit dem Blick erfassen und so wahrnehmen.', 'Die Umgebung mithilfe der Augen aufnehmen und unterscheiden.'], onePointAnswers: ['Mit den Augen wahrnehmen.', 'Etwas erblicken.', 'Das tun, wozu man Augen hat.', 'Etwas anschauen und bemerken.', 'Im Hellen die Dinge erkennen.', 'Den Blick auf etwas richten.'], thetaValue: -2.0),
      VocabularyItem(word: 'Auto', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Mit einem Motor angetriebenes Fahrzeug auf Rädern für den Straßenverkehr.', 'Vierrädriges Kraftfahrzeug, mit dem man Personen befördert.', 'Motorbetriebenes Gefährt, das man steuert und auf Straßen fährt.', 'Geschlossenes Straßenfahrzeug mit Motor, das man lenkt und fährt.'], onePointAnswers: ['Ein Fahrzeug mit vier Rädern.', 'Womit man auf der Straße fährt.', 'Ein Wagen mit Motor.', 'Etwas, das tankt und fährt.', 'Steht oft in der Garage.', 'Man braucht einen Führerschein dafür.'], thetaValue: -2.0),
      VocabularyItem(word: 'schön', frequency: WordFrequency.veryHigh, twoPointAnswers: ['So beschaffen, dass es beim Betrachten Wohlgefallen und Freude weckt.', 'Von einem Aussehen, das als angenehm und ansprechend empfunden wird.', 'Den Sinnen oder dem Empfinden auf angenehme Weise gefallend.', 'So gestaltet, dass man es gerne ansieht oder erlebt.'], onePointAnswers: ['Angenehm anzusehen.', 'Hübsch.', 'Gefällt einem gut.', 'Das Gegenteil von hässlich.', 'Was Freude beim Betrachten macht.', 'Wie ein Sonnenuntergang.'], thetaValue: -2.0),
      VocabularyItem(word: 'Freund', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Mensch, mit dem man durch Zuneigung und Vertrauen verbunden ist.', 'Vertraute Person, die einem nahesteht und auf die man sich verlassen kann.', 'Jemand, mit dem man eine enge, vertraute Beziehung pflegt.', 'Person, die man mag und mit der man gern Zeit verbringt.'], onePointAnswers: ['Jemand, den man mag.', 'Eine vertraute Person.', 'Mit wem man gern zusammen ist.', 'Das Gegenteil von Feind.', 'Jemand, dem man vertraut.', 'Ein guter Kumpel.'], thetaValue: -2.0),
      VocabularyItem(word: 'kaufen', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Eine Ware gegen Geld erwerben und so zu seinem Eigentum machen.', 'Etwas durch Bezahlen eines Preises erwerben.', 'Gegen Bezahlung einen Gegenstand von einem Händler übernehmen.', 'Geld geben, um dafür eine Sache zu bekommen.'], onePointAnswers: ['Für Geld etwas bekommen.', 'Im Laden einen Preis bezahlen.', 'Etwas erwerben.', 'Das Gegenteil davon, etwas gegen Geld herzugeben.', 'Im Geschäft eine Ware mitnehmen und bezahlen.', 'Geld gegen eine Ware tauschen.'], thetaValue: -2.0),
      VocabularyItem(word: 'schnell', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Mit hoher Geschwindigkeit, also in kurzer Zeit eine Strecke zurücklegend.', 'So, dass etwas in nur wenig Zeit geschieht oder abläuft.', 'Sich rasch bewegend oder rasch geschehend.', 'Eine große Geschwindigkeit aufweisend oder ohne Verzögerung erfolgend.'], onePointAnswers: ['Nicht langsam.', 'Mit hohem Tempo.', 'In kurzer Zeit.', 'Wie ein Rennwagen.', 'Ohne lange zu warten.', 'Rasch oder flink.'], thetaValue: -2.0),
      VocabularyItem(word: 'Hand', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Vorderer, greifender Teil des Arms mit fünf Fingern.', 'Körperteil am Ende des Arms, mit dem man greift und festhält.', 'Das mit Fingern versehene Ende des Arms, mit dem man Dinge anfasst.', 'Greiforgan am unteren Ende des Arms, das fünf Finger besitzt.'], onePointAnswers: ['Damit greift man Dinge.', 'Das Ende des Arms.', 'Hat fünf Finger.', 'Womit man jemandem zum Gruß die seine reicht.', 'Womit man schreibt und winkt.', 'Ein Körperteil zum Festhalten.'], thetaValue: -2.0),
    ],
    // high (17 items)
    [
      VocabularyItem(word: 'Buch', frequency: WordFrequency.high, twoPointAnswers: ['Eine Sammlung bedruckter, gebundener Seiten zum Lesen.', 'Ein gebundenes Druckwerk aus vielen Blättern, das einen Text oder Bilder enthält.', 'Mehrere zusammengeheftete Seiten mit einem Einband, in denen eine Geschichte oder Wissen festgehalten ist.'], onePointAnswers: ['Etwas zum Lesen.', 'Bedruckte Seiten mit Einband.', 'Ein Werk eines Schriftstellers.', 'Ein Roman oder Sachwerk.', 'Viele Seiten zwischen zwei Deckeln.'], thetaValue: -1.0),
      VocabularyItem(word: 'arbeiten', frequency: WordFrequency.high, twoPointAnswers: ['Eine Tätigkeit ausüben, um etwas herzustellen, zu leisten oder Geld zu verdienen.', 'Sich körperlich oder geistig anstrengen, um ein Ziel oder ein Ergebnis zu erreichen.', 'Einer Beschäftigung nachgehen, mit der man seinen Lebensunterhalt verdient.'], onePointAnswers: ['Einer Beschäftigung nachgehen.', 'Tätig sein, um Geld zu verdienen.', 'Sich anstrengen für ein Ziel.', 'Eine Aufgabe erledigen.', 'Einen Beruf ausüben.'], thetaValue: -1.0),
      VocabularyItem(word: 'Weg', frequency: WordFrequency.high, twoPointAnswers: ['Eine schmale Strecke, auf der man gehen oder fahren kann, um irgendwohin zu gelangen.', 'Die Strecke oder Route, die man zurücklegt, um von einem Ort zu einem anderen zu kommen.', 'Ein befestigter oder ausgetretener Pfad, der zwei Orte miteinander verbindet.'], onePointAnswers: ['Eine Strecke zum Gehen.', 'Ein Pfad.', 'Die Route zu einem Ziel.', 'Wo man entlangläuft.', 'Eine Verbindung zwischen Orten.'], thetaValue: -1.0),
      VocabularyItem(word: 'warm', frequency: WordFrequency.high, twoPointAnswers: ['Eine angenehm hohe Temperatur aufweisend, also weder kalt noch heiß.', 'So beschaffen, dass man eine angenehme Wärme empfindet.', 'Von mäßig hoher Temperatur, die ein wohliges Gefühl erzeugt.'], onePointAnswers: ['Nicht kalt.', 'Von angenehmer Wärme.', 'Eher heiß als kühl.', 'Mit milder Hitze.', 'Behaglich temperiert.'], thetaValue: -1.0),
      VocabularyItem(word: 'sprechen', frequency: WordFrequency.high, twoPointAnswers: ['Worte mit der Stimme äußern, um sich anderen mitzuteilen.', 'Sich mündlich durch Laute und Wörter ausdrücken.', 'Mit jemandem reden oder etwas mit der Stimme hörbar mitteilen.'], onePointAnswers: ['Reden.', 'Worte mit der Stimme äußern.', 'Sich mündlich mitteilen.', 'Etwas sagen.', 'Ein Gespräch führen.'], thetaValue: -1.0),
      VocabularyItem(word: 'Stadt', frequency: WordFrequency.high, twoPointAnswers: ['Eine größere Siedlung mit vielen Häusern, Straßen und Einwohnern.', 'Ein dicht bebauter Ort, der größer als ein Dorf ist und ein eigenes Verwaltungszentrum hat.', 'Ein bevölkerungsreicher Wohnort mit Geschäften, Behörden und einem dicht bebauten Zentrum.'], onePointAnswers: ['Ein großer Wohnort.', 'Größer als ein Dorf.', 'Ein Ort mit vielen Menschen und Häusern.', 'Eine Großsiedlung.', 'Ein Ballungsort mit Straßen und Plätzen.'], thetaValue: -1.0),
      VocabularyItem(word: 'Tier', frequency: WordFrequency.high, twoPointAnswers: ['Ein lebendes Wesen, das sich bewegen kann und im Unterschied zum Menschen und zur Pflanze steht.', 'Ein beseeltes Lebewesen wie etwa ein Hund, eine Katze oder ein Vogel.', 'Ein Geschöpf, das atmet, sich fortbewegt und Nahrung aufnimmt, aber nicht zu den Pflanzen zählt.'], onePointAnswers: ['Ein Lebewesen wie Hund oder Katze.', 'Kein Mensch und keine Pflanze.', 'Ein Geschöpf, das sich bewegt.', 'Etwa ein Vogel oder Fisch.', 'Ein nichtmenschliches Lebewesen.'], thetaValue: -1.0),
      VocabularyItem(word: 'Brief', frequency: WordFrequency.high, twoPointAnswers: ['Eine schriftliche Mitteilung, die man in einem Umschlag an jemanden schickt.', 'Ein auf Papier verfasster Text, den man jemandem mit der Post zusendet.', 'Eine persönliche oder geschäftliche Nachricht in geschriebener Form, die an einen Empfänger gerichtet ist.'], onePointAnswers: ['Eine schriftliche Nachricht.', 'Etwas, das man mit der Post schickt.', 'Eine Mitteilung auf Papier.', 'Was im Umschlag steckt.', 'Eine Botschaft an einen Empfänger.'], thetaValue: -1.0),
      VocabularyItem(word: 'Reise', frequency: WordFrequency.high, twoPointAnswers: ['Eine Fahrt an einen entfernten Ort, oft zur Erholung oder aus geschäftlichen Gründen.', 'Das Zurücklegen einer größeren Strecke, um vorübergehend an einen anderen Ort zu gelangen.', 'Ein Aufbruch in die Ferne mit einem Verkehrsmittel, um fremde Orte zu besuchen oder zu arbeiten.'], onePointAnswers: ['Eine Fahrt in die Ferne.', 'Wenn man fortfährt, um fremde Orte zu sehen.', 'Ein Ausflug an einen fernen Ort.', 'Eine längere Tour.', 'Der Weg in den Urlaub.'], thetaValue: -1.0),
      VocabularyItem(word: 'Wetter', frequency: WordFrequency.high, twoPointAnswers: ['Der Zustand der Luft an einem Ort, etwa ob es regnet, schneit oder die Sonne scheint.', 'Die augenblicklichen Verhältnisse von Temperatur, Wind und Niederschlag in der Luft.', 'Der wechselnde Zustand draußen, der über Sonne, Regen, Wind und Kälte bestimmt wird.'], onePointAnswers: ['Ob es regnet oder die Sonne scheint.', 'Der Zustand draußen.', 'Sonne, Regen oder Schnee.', 'Wie die Luft draußen ist.', 'Was der Himmel zeigt.'], thetaValue: -1.0),
      VocabularyItem(word: 'Gefühl', frequency: WordFrequency.high, twoPointAnswers: ['Eine innere Empfindung wie Freude, Trauer, Angst oder Wut.', 'Eine seelische Regung, die man in sich wahrnimmt, ohne sie zu denken.', 'Ein Zustand des Inneren, der zum Beispiel als Glück, Schmerz oder Liebe erlebt wird.'], onePointAnswers: ['Eine innere Empfindung.', 'Etwa Freude oder Trauer.', 'Eine seelische Regung.', 'Was man im Herzen spürt.', 'Eine Stimmung in einem selbst.'], thetaValue: -1.0),
      VocabularyItem(word: 'Antwort', frequency: WordFrequency.high, twoPointAnswers: ['Eine Äußerung, mit der man auf eine Frage oder Aufforderung reagiert.', 'Die Reaktion in Worten, die jemand auf eine gestellte Frage gibt.', 'Das, was man entgegnet, wenn man gefragt oder angesprochen wird.'], onePointAnswers: ['Was man auf eine Frage sagt.', 'Eine Erwiderung.', 'Die Reaktion auf eine Frage.', 'Eine Entgegnung.', 'Was man zurückgibt, wenn man gefragt wird.'], thetaValue: -1.0),
      VocabularyItem(word: 'Geschichte', frequency: WordFrequency.high, twoPointAnswers: ['Eine Erzählung von Ereignissen, die sich wirklich oder erfunden zugetragen haben.', 'Ein berichteter Ablauf von Begebenheiten mit Anfang, Mitte und Ende.', 'Die Schilderung dessen, was früher geschehen ist, oder eine erfundene Erzählung.'], onePointAnswers: ['Eine Erzählung.', 'Etwas, das erzählt wird.', 'Ein Bericht über Ereignisse.', 'Was früher geschehen ist.', 'Eine erfundene oder wahre Begebenheit.'], thetaValue: -1.0),
      VocabularyItem(word: 'Erfahrung', frequency: WordFrequency.high, twoPointAnswers: ['Das Wissen und Können, das man durch eigenes Erleben gewonnen hat.', 'Die im Laufe der Zeit durch Übung und Erlebnisse erworbene Kenntnis.', 'Etwas, das man selbst durchlebt hat und woraus man für die Zukunft lernt.'], onePointAnswers: ['Was man durch Erlebtes gelernt hat.', 'Wissen aus der Praxis.', 'Routine durch Übung.', 'Was man im Leben dazugelernt hat.', 'Erworbene Menschenkenntnis oder Können.'], thetaValue: -1.0),
      VocabularyItem(word: 'wichtig', frequency: WordFrequency.high, twoPointAnswers: ['Von großer Bedeutung, sodass es nicht übergangen werden darf.', 'So beschaffen, dass es einen erheblichen Einfluss hat und beachtet werden muss.', 'Von Belang und Gewicht, also nicht nebensächlich oder gleichgültig.'], onePointAnswers: ['Von großer Bedeutung.', 'Nicht nebensächlich.', 'Etwas, das zählt.', 'Von Belang.', 'Was man beachten muss.'], thetaValue: -1.0),
      VocabularyItem(word: 'entscheiden', frequency: WordFrequency.high, twoPointAnswers: ['Sich nach Abwägung für eine von mehreren Möglichkeiten festlegen.', 'Eine Wahl treffen und damit eine Sache endgültig bestimmen.', 'Zu einem festen Schluss kommen, wie in einer offenen Frage verfahren werden soll.'], onePointAnswers: ['Eine Wahl treffen.', 'Sich für etwas festlegen.', 'Eine Sache bestimmen.', 'Sich zwischen Möglichkeiten festlegen.', 'Einen Schluss fassen.'], thetaValue: -1.0),
      VocabularyItem(word: 'deutlich', frequency: WordFrequency.high, twoPointAnswers: ['Klar und gut wahrnehmbar, sodass kein Zweifel bleibt.', 'So beschaffen, dass etwas eindeutig zu erkennen oder zu verstehen ist.', 'Klar erkennbar und unmissverständlich in Form, Ton oder Aussage.'], onePointAnswers: ['Klar erkennbar.', 'Gut zu verstehen.', 'Nicht verschwommen.', 'Eindeutig.', 'Unmissverständlich.'], thetaValue: -1.0),
    ],
    // medium (16 items)
    [
      VocabularyItem(word: 'Zweifel', frequency: WordFrequency.medium, twoPointAnswers: ['Unsicheres Gefühl, ob etwas wahr, richtig oder möglich ist.', 'Zustand, in dem man sich einer Sache nicht sicher ist und sie infrage stellt.', 'Innere Unentschlossenheit, weil man eine Behauptung für nicht gesichert hält.', 'Mangel an Gewissheit, der einen daran hindert, fest an etwas zu glauben.'], onePointAnswers: ['Wenn man sich nicht sicher ist.', 'Das Gegenteil von fester Überzeugung.', 'Zum Beispiel, wenn man eine Aussage für nicht gesichert hält.', 'Etwas infrage stellen.', 'Wenn man nicht recht glauben mag.', 'Eine offene Frage im Kopf.'], thetaValue: 0.0),
      VocabularyItem(word: 'Vorurteil', frequency: WordFrequency.medium, twoPointAnswers: ['Vorgefasste Meinung über jemanden oder etwas, ohne diese geprüft zu haben.', 'Festes Urteil über eine Gruppe, das nicht auf eigener Erfahrung beruht.', 'Voreingenommene Ansicht, die man schon vor jeder Begegnung im Kopf hat.', 'Pauschale Bewertung anderer, die meist auf Klischees statt auf Tatsachen fußt.'], onePointAnswers: ['Wenn man jemanden vorschnell beurteilt.', 'Eine Meinung ohne echte Kenntnis.', 'Zum Beispiel über eine ganze Gruppe von Menschen.', 'Voreingenommen sein.', 'Etwas, das auf Klischees beruht.', 'Eine ungerechte vorgefasste Ansicht.'], thetaValue: 0.0),
      VocabularyItem(word: 'Gerücht', frequency: WordFrequency.medium, twoPointAnswers: ['Unbestätigte Nachricht, die von Mund zu Mund weitergegeben wird.', 'Behauptung, die sich verbreitet, ohne dass man weiß, ob sie stimmt.', 'Erzählung, die unter Leuten kursiert und meist nicht belegt ist.', 'Ungeprüfte Neuigkeit, die heimlich von Person zu Person wandert.'], onePointAnswers: ['Etwas, das man sich erzählt, ohne es zu wissen.', 'Eine unbestätigte Neuigkeit.', 'Zum Beispiel über einen Nachbarn getuschelt.', 'Verbreitet sich schnell unter Leuten.', 'Niemand weiß, ob es stimmt.', 'Gerede, das die Runde macht.'], thetaValue: 0.0),
      VocabularyItem(word: 'Hindernis', frequency: WordFrequency.medium, twoPointAnswers: ['Etwas, das einem im Weg steht und das Vorankommen erschwert.', 'Schwierigkeit oder Sperre, die man überwinden muss, um ein Ziel zu erreichen.', 'Sache oder Umstand, der einen daran hindert, weiterzukommen.', 'Barriere, die den Fortgang einer Bewegung oder eines Vorhabens aufhält.'], onePointAnswers: ['Etwas, das im Weg steht.', 'Muss überwunden werden.', 'Zum Beispiel ein Zaun beim Laufen.', 'Eine Schwierigkeit auf dem Weg zum Ziel.', 'Hält einen auf.', 'Eine Sperre, die das Vorankommen bremst.'], thetaValue: 0.0),
      VocabularyItem(word: 'Neugier', frequency: WordFrequency.medium, twoPointAnswers: ['Starkes Verlangen, Neues zu erfahren oder etwas Verborgenes zu erkunden.', 'Lebhaftes Interesse, das einen zum Fragen und Nachforschen treibt.', 'Drang, mehr über etwas wissen zu wollen, was einem unbekannt ist.', 'Bedürfnis, Dinge zu entdecken und ihnen auf den Grund zu gehen.'], onePointAnswers: ['Wenn man unbedingt etwas wissen will.', 'Treibt Kinder zum ständigen Fragen.', 'Zum Beispiel, wenn man ins fremde Zimmer schaut.', 'Lust, Neues zu entdecken.', 'Das Gegenteil von Gleichgültigkeit.', 'Wissensdurst.'], thetaValue: 0.0),
      VocabularyItem(word: 'Erinnerung', frequency: WordFrequency.medium, twoPointAnswers: ['Bild oder Eindruck von etwas Vergangenem, das im Gedächtnis bewahrt wird.', 'Das, was vom Erlebten im Kopf zurückbleibt und wieder wachgerufen werden kann.', 'Gedankliches Festhalten früherer Ereignisse oder Personen.', 'Vorstellung von etwas, das man früher erlebt oder gelernt hat.'], onePointAnswers: ['Was im Gedächtnis bleibt.', 'Zum Beispiel an die Kindheit.', 'Ein altes Foto ruft sie hervor.', 'Das Gegenteil von Vergessen.', 'Was vom Erlebten zurückbleibt.', 'Etwas Vergangenes im Kopf.'], thetaValue: 0.0),
      VocabularyItem(word: 'Verzweiflung', frequency: WordFrequency.medium, twoPointAnswers: ['Zustand tiefer Hoffnungslosigkeit, in dem man keinen Ausweg mehr sieht.', 'Seelische Not, bei der einem alles aussichtslos erscheint.', 'Gefühl völliger Mutlosigkeit, weil man glaubt, nichts mehr ändern zu können.', 'Tiefe innere Bedrängnis ohne jede Aussicht auf Besserung.'], onePointAnswers: ['Wenn man keinen Ausweg mehr sieht.', 'Völlige Hoffnungslosigkeit.', 'Zum Beispiel nach einem schweren Verlust.', 'Wenn man am Ende seiner Kräfte ist.', 'Tiefe Mutlosigkeit.', 'Das Gegenteil von Zuversicht.'], thetaValue: 0.0),
      VocabularyItem(word: 'großzügig', frequency: WordFrequency.medium, twoPointAnswers: ['Bereit, anderen gern und reichlich etwas zu geben.', 'So, dass man freigebig ist und nicht kleinlich auf den eigenen Vorteil achtet.', 'Gern teilend und über kleine Fehler hinwegsehend.', 'Freigebig und weitherzig im Umgang mit anderen.'], onePointAnswers: ['Wenn jemand gern gibt und teilt.', 'Das Gegenteil von geizig.', 'Zum Beispiel ein dickes Trinkgeld.', 'Nicht kleinlich.', 'Sieht über kleine Fehler hinweg.', 'Freigebig.'], thetaValue: 0.0),
      VocabularyItem(word: 'hartnäckig', frequency: WordFrequency.medium, twoPointAnswers: ['So, dass man trotz Widerstand beharrlich an einer Sache festhält.', 'Nicht nachgebend und unermüdlich ein Ziel verfolgend.', 'Beharrlich und schwer von etwas abzubringen.', 'Sich zäh und ausdauernd nicht abschütteln lassend.'], onePointAnswers: ['Wenn man nicht aufgibt.', 'Beharrlich bleiben.', 'Zum Beispiel ein Husten, der nicht weggeht.', 'Sich nicht abbringen lassen.', 'Das Gegenteil von schnell aufgebend.', 'Zäh dranbleiben.'], thetaValue: 0.0),
      VocabularyItem(word: 'gelassen', frequency: WordFrequency.medium, twoPointAnswers: ['Ruhig und ausgeglichen, auch wenn es schwierig wird.', 'So, dass man die Fassung bewahrt und sich nicht aus der Ruhe bringen lässt.', 'Innerlich ruhig und ohne Aufregung einer Lage begegnend.', 'Besonnen und unaufgeregt, selbst unter Druck.'], onePointAnswers: ['Wenn man ruhig bleibt.', 'Sich nicht aus der Ruhe bringen lassen.', 'Das Gegenteil von nervös.', 'Zum Beispiel ruhig bei einer Prüfung.', 'Innerlich ausgeglichen.', 'Die Fassung bewahren.'], thetaValue: 0.0),
      VocabularyItem(word: 'verzichten', frequency: WordFrequency.medium, twoPointAnswers: ['Etwas, worauf man Anspruch hätte, freiwillig nicht nehmen oder aufgeben.', 'Bewusst auf etwas Angenehmes oder Zustehendes nicht bestehen und es lassen.', 'Aus eigenem Entschluss den Gebrauch oder Besitz einer Sache aufgeben.', 'Sich von etwas zurückziehen, das man haben dürfte oder könnte.'], onePointAnswers: ['Etwas freiwillig nicht nehmen.', 'Auf etwas Schönes von sich aus nicht bestehen.', 'Zum Beispiel beim Fasten keine Süßigkeiten nehmen.', 'Bewusst weglassen.', 'Aufgeben, obwohl man dürfte.', 'Nicht in Anspruch nehmen.'], thetaValue: 0.0),
      VocabularyItem(word: 'vermeiden', frequency: WordFrequency.medium, twoPointAnswers: ['Dafür sorgen, dass etwas Unangenehmes gar nicht erst geschieht.', 'Einer Sache aus dem Weg gehen, um sie nicht eintreten zu lassen.', 'So handeln, dass man einer unerwünschten Lage entgeht.', 'Etwas absichtlich umgehen oder unterlassen.'], onePointAnswers: ['Etwas nicht passieren lassen.', 'Einer Sache aus dem Weg gehen.', 'Zum Beispiel einen Streit umgehen.', 'Bewusst unterlassen.', 'Dafür sorgen, dass es nicht eintritt.', 'Etwas umgehen.'], thetaValue: 0.0),
      VocabularyItem(word: 'bewundern', frequency: WordFrequency.medium, twoPointAnswers: ['Jemanden oder etwas mit großer Anerkennung und Staunen betrachten.', 'Etwas wegen seiner Vorzüge sehr schätzen und voller Achtung ansehen.', 'Voller Hochachtung auf eine Leistung oder Eigenschaft blicken.', 'Etwas als großartig empfinden und ihm staunende Anerkennung zollen.'], onePointAnswers: ['Wenn man jemanden sehr schätzt.', 'Mit Staunen betrachten.', 'Zum Beispiel einen großen Künstler.', 'Voller Hochachtung ansehen.', 'Etwas großartig finden.', 'Zu jemandem aufschauen.'], thetaValue: 0.0),
      VocabularyItem(word: 'zögern', frequency: WordFrequency.medium, twoPointAnswers: ['Mit einer Handlung warten, weil man unsicher oder unentschlossen ist.', 'Vor einer Entscheidung zaudern und nicht gleich handeln.', 'Aus Unsicherheit eine Weile innehalten, statt sofort zu reagieren.', 'Unschlüssig sein und den Augenblick des Handelns hinausschieben.'], onePointAnswers: ['Nicht gleich handeln.', 'Aus Unsicherheit warten.', 'Zum Beispiel vor dem Sprung ins kalte Wasser.', 'Unentschlossen innehalten.', 'Zaudern.', 'Das Gegenteil von sofort zugreifen.'], thetaValue: 0.0),
      VocabularyItem(word: 'schwören', frequency: WordFrequency.medium, twoPointAnswers: ['Feierlich und mit Nachdruck versichern, dass etwas wahr ist oder getan wird.', 'Ein bindendes Versprechen ablegen, oft unter Anrufung von etwas Heiligem.', 'Mit größter Ernsthaftigkeit beteuern, dass man Wort halten wird.', 'Förmlich geloben, eine Pflicht zu erfüllen oder die Wahrheit zu sagen.'], onePointAnswers: ['Etwas ganz fest versprechen.', 'Feierlich beteuern.', 'Zum Beispiel vor Gericht die Wahrheit.', 'Ein bindendes Gelöbnis ablegen.', 'Hoch und heilig versichern.', 'Sein Wort verpfänden.'], thetaValue: 0.0),
      VocabularyItem(word: 'schlicht', frequency: WordFrequency.medium, twoPointAnswers: ['Einfach und ohne überflüssigen Schmuck oder Aufwand.', 'So gestaltet, dass es schmucklos und unauffällig wirkt.', 'Bescheiden und ohne Prunk, klar in der Form.', 'Nüchtern und einfach, ohne alles Überflüssige.'], onePointAnswers: ['Einfach und ohne Schmuck.', 'Das Gegenteil von prunkvoll.', 'Zum Beispiel ein schmuckloses Kleid.', 'Ohne Schnörkel.', 'Bescheiden gestaltet.', 'Klar und unauffällig.'], thetaValue: 0.0),
    ],
    // low (15 items)
    [
      VocabularyItem(word: 'Wehmut', frequency: WordFrequency.low, twoPointAnswers: ['ein stilles, sanftes Gefühl der Trauer, das oft mit der Erinnerung an Vergangenes oder mit dem Bewusstsein der Vergänglichkeit verbunden ist', 'eine zugleich schmerzliche und süße Stimmung der Sehnsucht nach etwas Verlorenem oder Unwiederbringlichem', 'leiser Kummer, der nicht aus akutem Leid, sondern aus melancholischer Rückschau entsteht'], onePointAnswers: ['eine traurige Sehnsucht', 'melancholische Stimmung', 'leise Trauer', 'ein bittersüßes Gefühl', 'Schwermut beim Abschied'], thetaValue: 1.0),
      VocabularyItem(word: 'beschwichtigen', frequency: WordFrequency.low, twoPointAnswers: ['jemanden durch begütigende Worte oder Gesten beruhigen, damit Erregung, Ärger oder Sorge nachlassen', 'eine aufgebrachte oder ängstliche Person zur Ruhe bringen und ihre Bedenken zerstreuen', 'einen Streit oder eine Aufregung dämpfen, indem man auf Mäßigung und Gelassenheit hinwirkt'], onePointAnswers: ['beruhigen', 'besänftigen', 'jemanden trösten und beruhigen', 'die Wogen glätten', 'eine Aufregung dämpfen'], thetaValue: 1.0),
      VocabularyItem(word: 'spröde', frequency: WordFrequency.low, twoPointAnswers: ['leicht zerbrechend oder reißend, weil es sich kaum verformen lässt, bevor es bricht', 'von einer Person: zurückhaltend, abweisend und nicht leicht zugänglich im Umgang', 'rau und trocken in der Beschaffenheit, etwa bei Haut oder Material, das keine Geschmeidigkeit aufweist'], onePointAnswers: ['leicht brüchig', 'abweisend und kühl', 'nicht biegsam', 'trocken und rissig', 'zerbrechlich', 'wenig zugänglich'], thetaValue: 1.0),
      VocabularyItem(word: 'Zwietracht', frequency: WordFrequency.low, twoPointAnswers: ['tiefe Uneinigkeit und feindselige Spannung zwischen Menschen oder Gruppen, die ihren Zusammenhalt zerstört', 'anhaltender Streit und Entzweiung, durch die ein vorher einträchtiges Verhältnis aufgelöst wird', 'ein Zustand der Verfeindung, in dem zuvor Verbundene gegeneinander stehen'], onePointAnswers: ['Streit und Uneinigkeit', 'Zerwürfnis', 'Feindschaft zwischen Parteien', 'das Gegenteil von Eintracht', 'Hader'], thetaValue: 1.0),
      VocabularyItem(word: 'verwegen', frequency: WordFrequency.low, twoPointAnswers: ['auf kühne, fast tollkühne Weise mutig, ohne Rücksicht auf Gefahr oder mögliche Folgen', 'von draufgängerischer Entschlossenheit geprägt, die bewusst ein hohes Risiko in Kauf nimmt', 'wagemutig bis zur Tollkühnheit, oft mit einem Hauch von Abenteuerlust und Trotz'], onePointAnswers: ['tollkühn', 'draufgängerisch', 'sehr mutig und risikofreudig', 'wagemutig', 'kühn bis zur Unvorsichtigkeit'], thetaValue: 1.0),
      VocabularyItem(word: 'Tücke', frequency: WordFrequency.low, twoPointAnswers: ['hinterhältige Bosheit, die sich hinter freundlichem Schein verbirgt und auf heimliche Schädigung zielt', 'eine versteckte, schwer vorhersehbare Gefahr oder Schwierigkeit, die sich plötzlich zeigt', 'die boshafte Eigenschaft, anderen durch verschlagenes Handeln Schaden zuzufügen'], onePointAnswers: ['Hinterlist', 'verborgene Gefahr', 'heimtückische Bosheit', 'eine versteckte Schwierigkeit', 'Arglist'], thetaValue: 1.0),
      VocabularyItem(word: 'darben', frequency: WordFrequency.low, twoPointAnswers: ['in großer Not leben und das Nötigste, vor allem Nahrung, entbehren müssen', 'über längere Zeit Mangel leiden und unter Armut oder Hunger schwer zu leiden haben', 'infolge von Knappheit ein kärgliches, entbehrungsreiches Dasein fristen'], onePointAnswers: ['Hunger leiden', 'Mangel leiden', 'in Armut leben', 'Not leiden', 'kaum genug zum Leben haben'], thetaValue: 1.0),
      VocabularyItem(word: 'Gepflogenheit', frequency: WordFrequency.low, twoPointAnswers: ['eine eingespielte, gewohnheitsmäßig befolgte Art und Weise, etwas zu tun, die sich über die Zeit eingebürgert hat', 'ein üblicher Brauch oder eine herkömmliche Übung innerhalb einer Gruppe oder eines Bereichs', 'ein eingeschliffener Usus, an den man sich aus Gewohnheit oder Sitte hält'], onePointAnswers: ['übliche Gewohnheit', 'Brauch', 'herkömmliche Praxis', 'eingespielte Sitte', 'übliche Verfahrensweise'], thetaValue: 1.0),
      VocabularyItem(word: 'hadern', frequency: WordFrequency.low, twoPointAnswers: ['mit einer Lage, dem Schicksal oder sich selbst innerlich unzufrieden ringen und nicht damit zurechtkommen', 'anhaltend mit jemandem oder etwas im Unfrieden sein und sich nicht damit abfinden können', 'grollend und unversöhnt mit einem Zustand kämpfen, ohne ihn innerlich annehmen zu können'], onePointAnswers: ['unzufrieden ringen', 'sich nicht abfinden können', 'mit dem Schicksal grollen', 'innerlich kämpfen', 'mit etwas im Unfrieden sein'], thetaValue: 1.0),
      VocabularyItem(word: 'Anmut', frequency: WordFrequency.low, twoPointAnswers: ['eine harmonische, mühelos wirkende Schönheit und Leichtigkeit in Bewegung, Haltung oder Erscheinung', 'die gefällige, gewinnende Eigenschaft, die etwas oder jemanden zugleich schön und liebreizend macht', 'die Eleganz und Grazie, mit der sich eine Person bewegt oder ausdrückt'], onePointAnswers: ['Grazie', 'liebreizende Schönheit', 'Eleganz der Bewegung', 'natürliche Zierlichkeit', 'graziöse Ausstrahlung'], thetaValue: 1.0),
      VocabularyItem(word: 'ergötzen', frequency: WordFrequency.low, twoPointAnswers: ['jemandem oder sich selbst durch etwas Unterhaltsames große Freude und heiteres Vergnügen bereiten', 'sich an einer angenehmen Sache mit Genuss und innerem Wohlbehagen weiden', 'Belustigung und Freude empfinden, indem man sich an etwas erfreut und labt'], onePointAnswers: ['sich amüsieren', 'großes Vergnügen bereiten', 'sich an etwas erfreuen', 'belustigen', 'Genuss empfinden'], thetaValue: 1.0),
      VocabularyItem(word: 'Bürde', frequency: WordFrequency.low, twoPointAnswers: ['eine schwere Last, meist im übertragenen Sinn als drückende Verpflichtung, Sorge oder Verantwortung', 'etwas, das jemanden seelisch oder moralisch belastet und nur mühsam zu tragen ist', 'eine als beschwerlich empfundene Pflicht, die man auf sich nimmt oder auferlegt bekommt'], onePointAnswers: ['schwere Last', 'drückende Verpflichtung', 'eine Belastung', 'schwere Verantwortung', 'etwas, das niederdrückt'], thetaValue: 1.0),
      VocabularyItem(word: 'beschaulich', frequency: WordFrequency.low, twoPointAnswers: ['von ruhiger, friedlicher Stille geprägt, die zum gelassenen Verweilen und Betrachten einlädt', 'still und gemächlich in der Lebensweise, ohne Hast und Aufregung, oft mit einem Hauch Idylle', 'auf besinnliche Ruhe ausgerichtet, in der man die Dinge in aller Gelassenheit auf sich wirken lässt'], onePointAnswers: ['ruhig und friedlich', 'besinnlich', 'gemächlich und still', 'idyllisch', 'von gelassener Stille'], thetaValue: 1.0),
      VocabularyItem(word: 'kargen', frequency: WordFrequency.low, twoPointAnswers: ['mit etwas geizig und sparsam umgehen und es nur zögernd oder in geringem Maße gewähren', 'etwas zurückhaltend bemessen, sodass jemand weniger bekommt, als angemessen oder gewünscht wäre', 'knausern und nicht freigebig sein, sondern das Vorhandene streng zurückhalten'], onePointAnswers: ['geizen', 'sparsam sein', 'knausern', 'etwas zurückhalten', 'knapp bemessen'], thetaValue: 1.0),
      VocabularyItem(word: 'verwerflich', frequency: WordFrequency.low, twoPointAnswers: ['moralisch so schlecht, dass es klare Ablehnung und Verurteilung verdient', 'in sittlicher Hinsicht nicht zu rechtfertigen und entschieden zu missbilligen', 'von einer Art, die als nicht hinnehmbar und tadelnswert gilt'], onePointAnswers: ['moralisch schlecht', 'verdammenswert', 'nicht zu rechtfertigen', 'tadelnswert', 'abzulehnen'], thetaValue: 1.0),
    ],
    // veryLow (11 items)
    [
      VocabularyItem(word: 'Mäander', frequency: WordFrequency.veryLow, twoPointAnswers: ['Eine ausgeprägte, schlingenförmige Windung im Lauf eines Flusses durch flaches Gelände.', 'Die kurvenreiche, sich vielfach krümmende Linienführung eines Wasserlaufs in einer Ebene.', 'Ein dekoratives Bandmuster aus rechtwinklig ineinander verschlungenen Linien, wie es in der antiken Kunst vorkommt.'], onePointAnswers: ['Eine Flussschlinge.', 'Eine starke Krümmung eines Flusses.', 'Wenn ein Fluss in großen Bögen verläuft.', 'Ein gewundenes Zierband in der Architektur.', 'Eine Schleife im Flusslauf.'], thetaValue: 2.0),
      VocabularyItem(word: 'inkommensurabel', frequency: WordFrequency.veryLow, twoPointAnswers: ['Mit einem gemeinsamen Maß nicht messbar und daher untereinander nicht vergleichbar.', 'So beschaffen, dass zwei Größen kein gemeinsames Vielfaches eines einheitlichen Maßstabs besitzen.', 'Nicht auf einen gemeinsamen Nenner oder Bewertungsmaßstab zurückführbar.'], onePointAnswers: ['Nicht vergleichbar.', 'Ohne gemeinsames Maß.', 'Nicht aufeinander beziehbar.', 'Zwei Dinge, die man nicht gegeneinander abwägen kann.', 'Unvereinbar im Maßstab.'], thetaValue: 2.0),
      VocabularyItem(word: 'Firlefanz', frequency: WordFrequency.veryLow, twoPointAnswers: ['Überflüssiges, wertloses Beiwerk, das nur dem äußeren Schein dient.', 'Unnützer Zierrat oder törichtes Getue ohne ernsthaften Gehalt.', 'Eine als albern empfundene Ansammlung belangloser Kleinigkeiten.'], onePointAnswers: ['Unnützes Zeug.', 'Wertloser Schnickschnack.', 'Überflüssiger Tand.', 'Alberner Kram.', 'Etwas Unwichtiges und Aufgesetztes.'], thetaValue: 2.0),
      VocabularyItem(word: 'konziliant', frequency: WordFrequency.veryLow, twoPointAnswers: ['Im Umgang um Ausgleich bemüht, nachgiebig und versöhnlich gestimmt.', 'Verbindlich und entgegenkommend, auf eine gütliche Verständigung bedacht.', 'Von freundlich-friedfertiger Haltung, die Gegensätze zu überbrücken sucht.'], onePointAnswers: ['Versöhnlich.', 'Entgegenkommend.', 'Nachgiebig im Umgang.', 'Um Ausgleich bemüht.', 'Verbindlich und friedfertig.'], thetaValue: 2.0),
      VocabularyItem(word: 'diaphan', frequency: WordFrequency.veryLow, twoPointAnswers: ['Lichtdurchlässig, sodass Licht hindurchscheinen kann, ohne völlig durchsichtig zu sein.', 'Von zarter, durchscheinender Beschaffenheit, durch die schwach Helligkeit dringt.', 'So fein und dünn, dass es Licht durchlässt und schimmernd wirkt.'], onePointAnswers: ['Durchscheinend.', 'Lichtdurchlässig.', 'Halb durchsichtig.', 'Schimmernd dünn.', 'Lässt Licht durch.'], thetaValue: 2.0),
      VocabularyItem(word: 'Galgenfrist', frequency: WordFrequency.veryLow, twoPointAnswers: ['Ein kurzer, letzter Aufschub vor einem unausweichlich drohenden Ende.', 'Eine knapp bemessene Verlängerung der Zeit, die einem Unheil vorausgeht.', 'Die letzte, gerade noch gewährte Spanne vor einer endgültigen Entscheidung.'], onePointAnswers: ['Ein letzter Aufschub.', 'Eine kurze Gnadenfrist.', 'Ein bisschen geschenkte Zeit vor dem Ende.', 'Eine knappe Verlängerung.', 'Ein Aufschub des Unvermeidlichen.'], thetaValue: 2.0),
      VocabularyItem(word: 'schmachten', frequency: WordFrequency.veryLow, twoPointAnswers: ['Unter Entbehrung oder sehnsüchtigem Verlangen leidend dahinleben.', 'Sich nach etwas oder jemandem mit qualvoller Sehnsucht verzehren.', 'Vor Hunger, Durst oder Sehnsucht in einem Zustand quälenden Mangels verharren.'], onePointAnswers: ['Sich heftig sehnen.', 'Vor Sehnsucht leiden.', 'Unter Mangel dahinleben.', 'Sehnsüchtig verlangen.', 'Vor Verlangen vergehen.'], thetaValue: 2.0),
      VocabularyItem(word: 'Konvolut', frequency: WordFrequency.veryLow, twoPointAnswers: ['Ein Bündel zusammengehöriger Schriftstücke oder Papiere.', 'Eine zusammengebundene oder gesammelte Menge von Dokumenten unterschiedlichen Inhalts.', 'Ein Stapel oder Paket von Akten, Briefen oder Drucksachen, das als Einheit behandelt wird.'], onePointAnswers: ['Ein Bündel Schriftstücke.', 'Eine Sammlung von Papieren.', 'Ein Aktenpaket.', 'Ein Stapel zusammengehöriger Dokumente.', 'Ein gebündelter Posten von Unterlagen.'], thetaValue: 2.0),
      VocabularyItem(word: 'Lamento', frequency: WordFrequency.veryLow, twoPointAnswers: ['Ein wortreiches, anhaltendes Klagen und Jammern über ein Missgeschick.', 'Eine larmoyante Beschwerde, die das eigene Leid weitschweifig vor anderen ausbreitet.', 'Ein wehleidiges Wehklagen, das mehr Aufsehen als Abhilfe sucht.'], onePointAnswers: ['Ein lautes Gejammer.', 'Anhaltende Klage.', 'Wehleidiges Klagen.', 'Eine umständliche Beschwerde.', 'Geklage über das eigene Unglück.'], thetaValue: 2.0),
      VocabularyItem(word: 'Eskapade', frequency: WordFrequency.veryLow, twoPointAnswers: ['Ein übermütiger, aus der Reihe tanzender Streich, der von den Regeln abweicht.', 'Ein gewagtes, abenteuerliches Vorhaben außerhalb des üblichen Rahmens.', 'Ein leichtfertiger Seitensprung vom geordneten Weg, oft mit anrüchigem Beigeschmack.'], onePointAnswers: ['Ein übermütiger Streich.', 'Ein abenteuerlicher Ausbruch.', 'Ein gewagter Ausrutscher.', 'Ein Abweichen vom üblichen Weg.', 'Ein leichtsinniges Wagnis.'], thetaValue: 2.0),
      VocabularyItem(word: 'obsolet', frequency: WordFrequency.veryLow, twoPointAnswers: ['Nicht mehr gebräuchlich und vom Lauf der Zeit überholt.', 'Veraltet und außer Gebrauch geraten, sodass es keine Geltung mehr besitzt.', 'Durch Neueres ersetzt und daher hinfällig geworden.'], onePointAnswers: ['Veraltet.', 'Überholt.', 'Nicht mehr gebräuchlich.', 'Außer Gebrauch.', 'Hinfällig geworden.'], thetaValue: 2.0),
    ],
  ];
}
