/// Banque d'items du sous-test Vocabulaire — es (GÉNÉRÉ par IA, vérifié). 5 bandes de fréquence. NE PAS éditer à la main.
library;

import 'vocabulary_generator.dart';

List<List<VocabularyItem>> buildSpanishVocabularyBanks() {
  return [
    // veryHigh (16 items)
    [
      VocabularyItem(word: 'casa', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Edificio o construcción destinada a que vivan en ella una o varias personas.', 'Vivienda donde alguien reside habitualmente con su familia.', 'Lugar cerrado y cubierto que sirve de morada y resguardo a las personas.'], onePointAnswers: ['El sitio donde uno vive.', 'Un hogar.', 'La vivienda de alguien.', 'Donde duermes y comes cada día.', 'Un piso o un chalet.'], thetaValue: -2.0),
      VocabularyItem(word: 'agua', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Líquido transparente, incoloro e insípido que forma ríos, mares y lluvia, y resulta esencial para la vida.', 'Sustancia líquida formada por hidrógeno y oxígeno que bebemos y usamos para lavar.', 'Elemento líquido que cae de las nubes en forma de lluvia y llena ríos, lagos y océanos.'], onePointAnswers: ['Lo que bebes cuando tienes sed.', 'Lo que sale del grifo.', 'Lo que llena el mar y los ríos.', 'El líquido de la lluvia.', 'Algo que sirve para beber y lavarse.'], thetaValue: -2.0),
      VocabularyItem(word: 'comer', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Tomar alimento por la boca, masticarlo y tragarlo para nutrir el cuerpo.', 'Ingerir comida para alimentarse y obtener energía.', 'Tomar los alimentos que el cuerpo necesita para mantenerse.'], onePointAnswers: ['Llevarse algo a la boca para alimentarse.', 'Tomar alimentos.', 'Lo que haces en el desayuno o la cena.', 'Alimentarse.', 'Masticar y tragar comida.'], thetaValue: -2.0),
      VocabularyItem(word: 'grande', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Que tiene un tamaño, una extensión o unas dimensiones superiores a lo normal.', 'Que supera en tamaño o cantidad a otras cosas de su misma clase.', 'De dimensiones considerables, mayor de lo habitual.'], onePointAnswers: ['Lo contrario de pequeño.', 'Que ocupa mucho espacio.', 'Que mide mucho.', 'De gran tamaño.', 'Que es muy amplio.'], thetaValue: -2.0),
      VocabularyItem(word: 'tiempo', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Magnitud que mide la sucesión de los acontecimientos y permite ordenar el pasado, el presente y el futuro.', 'Duración de las cosas, que se cuenta en segundos, horas, días o años.', 'Estado de la atmósfera en un lugar y momento determinados, como la lluvia o el sol.'], onePointAnswers: ['Lo que marca el reloj.', 'Las horas y los minutos.', 'Si hace sol o llueve.', 'Lo que pasa entre el ayer y el mañana.', 'La duración de algo.'], thetaValue: -2.0),
      VocabularyItem(word: 'trabajar', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Realizar una actividad física o intelectual a cambio de un sueldo o para conseguir un fin.', 'Ocuparse en un oficio o empleo para ganarse la vida.', 'Hacer un esfuerzo continuado para producir o conseguir algo.'], onePointAnswers: ['Tener un empleo.', 'Ir a la oficina o a la fábrica.', 'Ganar dinero haciendo algo.', 'Hacer una tarea por la que te pagan.', 'Esforzarse en una labor.'], thetaValue: -2.0),
      VocabularyItem(word: 'niño', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Persona que está en los primeros años de su vida, antes de llegar a la adolescencia.', 'Ser humano de corta edad, que aún no es adulto.', 'Persona joven que todavía está creciendo y va a la escuela.'], onePointAnswers: ['Un crío.', 'Una persona pequeña.', 'Alguien que va al colegio.', 'Lo contrario de un adulto.', 'Un chaval de pocos años.'], thetaValue: -2.0),
      VocabularyItem(word: 'rápido', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Que se mueve o sucede a gran velocidad, en poco tiempo.', 'Que emplea poco tiempo en hacer algo o en desplazarse.', 'Que actúa o avanza con mucha velocidad.'], onePointAnswers: ['Lo contrario de lento.', 'Que va muy deprisa.', 'Que tarda poco.', 'Veloz.', 'Que se mueve a gran velocidad.'], thetaValue: -2.0),
      VocabularyItem(word: 'ciudad', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Población grande con muchos habitantes, edificios, calles y servicios, donde se concentra la vida urbana.', 'Núcleo de población de tamaño importante, con comercios, oficinas y transporte público.', 'Conjunto urbano extenso y poblado, normalmente mayor que un pueblo.'], onePointAnswers: ['Un lugar con muchas casas y gente.', 'Lo contrario de un pueblo pequeño.', 'Madrid o Barcelona, por ejemplo.', 'Una urbe.', 'Un sitio grande con muchas calles.'], thetaValue: -2.0),
      VocabularyItem(word: 'amigo', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Persona con la que se mantiene una relación de afecto y confianza desinteresada.', 'Quien comparte cariño, trato frecuente y confianza con otra persona sin ser de su familia.', 'Persona a la que se quiere y en la que se confía por el trato y la simpatía mutua.'], onePointAnswers: ['Alguien al que aprecias.', 'Un compañero de confianza.', 'Una persona con quien te llevas bien.', 'Alguien que no es familia pero quieres mucho.', 'Un colega.'], thetaValue: -2.0),
      VocabularyItem(word: 'comprar', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Adquirir algo pagando un precio por ello.', 'Obtener un producto o servicio a cambio de dinero.', 'Hacerse con una cosa entregando dinero a quien la vende.'], onePointAnswers: ['Pagar por algo.', 'Conseguir algo con dinero.', 'Lo que haces en una tienda.', 'Adquirir un producto.', 'Lo contrario de vender.'], thetaValue: -2.0),
      VocabularyItem(word: 'noche', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Periodo de tiempo que transcurre desde que se pone el sol hasta que vuelve a amanecer.', 'Parte oscura del día, cuando no hay luz solar.', 'Espacio de oscuridad comprendido entre el atardecer y el amanecer.'], onePointAnswers: ['Cuando está oscuro.', 'Lo contrario del día.', 'El momento de dormir.', 'Cuando salen las estrellas.', 'Las horas sin sol.'], thetaValue: -2.0),
      VocabularyItem(word: 'calle', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Vía pública entre edificios o casas por donde transitan personas y vehículos.', 'Camino dentro de una población, con aceras y calzada, que comunica unos lugares con otros.', 'Espacio de paso al aire libre en una localidad, flanqueado por construcciones.'], onePointAnswers: ['Por donde andan los coches y la gente.', 'Lo que hay entre los edificios.', 'Una vía de la ciudad.', 'Donde están las aceras.', 'El sitio por el que paseas en el pueblo.'], thetaValue: -2.0),
      VocabularyItem(word: 'abrir', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Separar o quitar lo que cierra o tapa algo para dejar libre el paso o el interior.', 'Hacer que algo cerrado deje de estarlo, como una puerta o una caja.', 'Descubrir o destapar lo que estaba tapado para acceder a su contenido.'], onePointAnswers: ['Lo contrario de cerrar.', 'Quitar la tapa de algo.', 'Hacer que una puerta deje de estar cerrada.', 'Destapar una caja.', 'Dejar algo libre para entrar.'], thetaValue: -2.0),
      VocabularyItem(word: 'bonito', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Que resulta agradable y atractivo a la vista o a los sentidos.', 'Que tiene belleza o gracia y gusta cuando se mira.', 'Que produce una sensación grata por su buen aspecto.'], onePointAnswers: ['Que es agradable de ver.', 'Lo contrario de feo.', 'Que gusta mucho mirarlo.', 'Que tiene belleza.', 'Algo hermoso.'], thetaValue: -2.0),
      VocabularyItem(word: 'hablar', frequency: WordFrequency.veryHigh, twoPointAnswers: ['Emitir palabras con la voz para comunicarse y expresar ideas o sentimientos.', 'Comunicarse con otra persona mediante palabras dichas en voz alta.', 'Expresar mediante la voz lo que se piensa o se siente usando un idioma.'], onePointAnswers: ['Decir cosas con la voz.', 'Conversar con alguien.', 'Usar palabras para comunicarse.', 'Lo que haces al charlar con un amigo.', 'Soltar palabras por la boca.'], thetaValue: -2.0),
    ],
    // high (17 items)
    [
      VocabularyItem(word: 'esfuerzo', frequency: WordFrequency.high, twoPointAnswers: ['Empleo intenso de energía física o mental para lograr algo o vencer una dificultad.', 'Uso enérgico de las fuerzas o de la voluntad para conseguir un fin.', 'Trabajo costoso que alguien realiza para superar un obstáculo o alcanzar una meta.'], onePointAnswers: ['Cuando uno se emplea a fondo.', 'Lo que cuesta conseguir algo.', 'Poner mucha energía.', 'Sacrificio para lograr una meta.', 'Echarle ganas a una tarea.'], thetaValue: -1.0),
      VocabularyItem(word: 'aprovechar', frequency: WordFrequency.high, twoPointAnswers: ['Sacar el mayor provecho o utilidad posible de algo o de una ocasión.', 'Emplear bien una cosa o una oportunidad para obtener beneficio de ella.', 'Servirse de una circunstancia favorable antes de que se pierda.'], onePointAnswers: ['Sacar partido a algo.', 'Usar bien una ocasión.', 'No desperdiciar una oportunidad.', 'Hacer que algo resulte útil.', 'Exprimir una buena ocasión.'], thetaValue: -1.0),
      VocabularyItem(word: 'frontera', frequency: WordFrequency.high, twoPointAnswers: ['Línea que separa dos países o territorios y marca dónde acaba uno y empieza otro.', 'Límite que divide el terreno de un Estado del de otro vecino.', 'Confín que delimita hasta dónde llega la soberanía de una nación.'], onePointAnswers: ['El límite entre dos países.', 'Donde acaba un Estado.', 'La raya que separa naciones.', 'El paso de un país a otro.', 'El borde de un territorio.'], thetaValue: -1.0),
      VocabularyItem(word: 'escaso', frequency: WordFrequency.high, twoPointAnswers: ['Que existe en poca cantidad o no llega a lo que se necesita.', 'Que resulta insuficiente o que apenas alcanza para algo.', 'Que es corto o limitado respecto de lo que sería deseable.'], onePointAnswers: ['Que hay poco.', 'Lo contrario de abundante.', 'Que no llega para todos.', 'Insuficiente.', 'Que falta o casi no hay.'], thetaValue: -1.0),
      VocabularyItem(word: 'mejorar', frequency: WordFrequency.high, twoPointAnswers: ['Hacer que algo pase a un estado mejor o más conveniente que el anterior.', 'Cambiar una cosa de modo que aumente su calidad o su valor.', 'Recuperar la salud o ganar en bienestar tras una enfermedad o un mal momento.'], onePointAnswers: ['Hacer que algo vaya mejor.', 'Pasar a estar mejor.', 'Lo contrario de empeorar.', 'Recuperarse de una enfermedad.', 'Perfeccionar una cosa.'], thetaValue: -1.0),
      VocabularyItem(word: 'descubrir', frequency: WordFrequency.high, twoPointAnswers: ['Hallar o llegar a conocer algo que estaba oculto o que no se sabía.', 'Encontrar por primera vez algo desconocido hasta entonces.', 'Quitar lo que tapa una cosa para dejarla a la vista.'], onePointAnswers: ['Encontrar algo nuevo.', 'Sacar a la luz lo oculto.', 'Llegar a saber algo que se ignoraba.', 'Destapar una cosa.', 'Dar con algo escondido.'], thetaValue: -1.0),
      VocabularyItem(word: 'frágil', frequency: WordFrequency.high, twoPointAnswers: ['Que se rompe o se estropea con facilidad.', 'Que tiene poca resistencia y se quiebra al menor golpe.', 'Que es delicado y puede dañarse sin apenas esfuerzo.'], onePointAnswers: ['Que se rompe enseguida.', 'Lo contrario de resistente.', 'Que se estropea con facilidad.', 'Delicado.', 'Que aguanta poco.'], thetaValue: -1.0),
      VocabularyItem(word: 'costumbre', frequency: WordFrequency.high, twoPointAnswers: ['Manera habitual de obrar que se repite con frecuencia por hábito.', 'Práctica adquirida por la repetición de los mismos actos.', 'Modo de proceder establecido por el uso a lo largo del tiempo.'], onePointAnswers: ['Algo que se hace siempre.', 'Un hábito.', 'Lo que uno repite por rutina.', 'Una práctica de toda la vida.', 'Lo que se suele hacer.'], thetaValue: -1.0),
      VocabularyItem(word: 'asombro', frequency: WordFrequency.high, twoPointAnswers: ['Sorpresa muy grande ante algo inesperado o admirable.', 'Impresión fuerte de extrañeza que causa algo fuera de lo común.', 'Estado de quien queda pasmado al ver o saber una cosa sorprendente.'], onePointAnswers: ['Una sorpresa enorme.', 'Quedarse pasmado.', 'Lo que se siente ante algo increíble.', 'Gran extrañeza.', 'Admiración por algo inesperado.'], thetaValue: -1.0),
      VocabularyItem(word: 'vínculo', frequency: WordFrequency.high, twoPointAnswers: ['Unión o lazo que liga a una persona o cosa con otra.', 'Relación estrecha que une a dos o más personas, ideas o hechos.', 'Atadura que mantiene conectadas entre sí dos realidades.'], onePointAnswers: ['Un lazo entre dos cosas.', 'Una unión o relación.', 'Lo que liga a unas personas con otras.', 'Una conexión.', 'Aquello que mantiene unidos a dos.'], thetaValue: -1.0),
      VocabularyItem(word: 'sencillo', frequency: WordFrequency.high, twoPointAnswers: ['Que no tiene complicación ni adornos y resulta fácil de entender o de usar.', 'Que carece de dificultad o de elementos innecesarios.', 'Que es natural y llano en el trato, sin presunción.'], onePointAnswers: ['Que es fácil.', 'Lo contrario de complicado.', 'Sin adornos ni lujos.', 'Llano en el trato.', 'Que no tiene complicación.'], thetaValue: -1.0),
      VocabularyItem(word: 'lograr', frequency: WordFrequency.high, twoPointAnswers: ['Conseguir lo que se desea o se pretende tras un esfuerzo.', 'Alcanzar un objetivo o un resultado que se buscaba.', 'Llegar a obtener algo que costaba o que parecía difícil.'], onePointAnswers: ['Conseguir algo.', 'Alcanzar una meta.', 'Salir bien una cosa que se buscaba.', 'Obtener lo que se quería.', 'Llegar a lo que uno se proponía.'], thetaValue: -1.0),
      VocabularyItem(word: 'vergüenza', frequency: WordFrequency.high, twoPointAnswers: ['Sentimiento penoso que produce el haber cometido una falta o el quedar en ridículo.', 'Turbación del ánimo causada por una acción humillante o deshonrosa.', 'Incomodidad que se siente ante los demás por temor a quedar mal.'], onePointAnswers: ['Lo que se siente al hacer el ridículo.', 'Sentirse mal por una falta.', 'Cuando uno se pone colorado.', 'Apuro ante los demás.', 'Sonrojo por algo embarazoso.'], thetaValue: -1.0),
      VocabularyItem(word: 'miedo', frequency: WordFrequency.high, twoPointAnswers: ['Sensación de angustia ante un peligro real o imaginado.', 'Estado de inquietud y temor provocado por algo que se considera una amenaza.', 'Emoción desagradable que se siente ante la idea de sufrir un daño o un mal.'], onePointAnswers: ['Temor.', 'Lo que se siente ante el peligro.', 'Sensación de pavor.', 'Lo que provoca una película de terror.', 'Una emoción de susto.'], thetaValue: -1.0),
      VocabularyItem(word: 'limpio', frequency: WordFrequency.high, twoPointAnswers: ['Que no tiene suciedad, manchas ni impurezas.', 'Que está libre de polvo, mugre o cualquier cosa que ensucie.', 'Que ha sido lavado o cuidado de modo que no queda nada sucio en él.'], onePointAnswers: ['Sin suciedad.', 'Lo contrario de sucio.', 'Que está bien lavado.', 'Sin manchas.', 'Aseado.'], thetaValue: -1.0),
      VocabularyItem(word: 'ayudar', frequency: WordFrequency.high, twoPointAnswers: ['Prestar a alguien colaboración o auxilio para que consiga algo o salga de un apuro.', 'Hacer algo para facilitar a otra persona una tarea o aliviar una dificultad.', 'Cooperar con alguien aportando esfuerzo o medios para su beneficio.'], onePointAnswers: ['Echar una mano.', 'Colaborar con alguien.', 'Auxiliar a otro.', 'Hacer un favor.', 'Apoyar a una persona.'], thetaValue: -1.0),
      VocabularyItem(word: 'prudente', frequency: WordFrequency.high, twoPointAnswers: ['Que actúa con cautela y reflexión para evitar daños o errores.', 'Que obra con moderación y sensatez, pensando en las consecuencias.', 'Que es sensato y previsor al decidir o al hablar.'], onePointAnswers: ['Que actúa con cautela.', 'Sensato.', 'Que piensa antes de actuar.', 'Que mide bien los riesgos.', 'Que es precavido.'], thetaValue: -1.0),
    ],
    // medium (14 items)
    [
      VocabularyItem(word: 'cobarde', frequency: WordFrequency.medium, twoPointAnswers: ['Que se deja dominar fácilmente por el miedo y no se atreve a afrontar el peligro o la dificultad.', 'Persona que carece de valor y rehúye los riesgos o las situaciones que exigen coraje.', 'Dicho de alguien que actúa de manera vil o pusilánime ante una amenaza, evitando enfrentarla.'], onePointAnswers: ['El que tiene mucho miedo.', 'Lo contrario de valiente.', 'Alguien sin valor.', 'Miedoso, gallina.', 'Que huye del peligro.'], thetaValue: 0.0),
      VocabularyItem(word: 'agotar', frequency: WordFrequency.medium, twoPointAnswers: ['Consumir por completo algo hasta que no quede nada de ello.', 'Cansar muchísimo a una persona o un animal, dejándolo sin fuerzas.', 'Gastar totalmente las existencias, las reservas o las posibilidades de algo.'], onePointAnswers: ['Acabar con todo.', 'Dejar muy cansado.', 'Quedarse sin nada.', 'Vaciar del todo.', 'Terminarse las existencias.'], thetaValue: 0.0),
      VocabularyItem(word: 'sospechar', frequency: WordFrequency.medium, twoPointAnswers: ['Imaginar o creer algo a partir de indicios o señales, sin tener certeza completa.', 'Desconfiar de una persona por suponer que ha hecho o hará algo malo.', 'Suponer la existencia de algo basándose en conjeturas o pruebas indirectas.'], onePointAnswers: ['Pensar que algo puede ser.', 'Desconfiar de alguien.', 'Tener una corazonada.', 'Imaginar sin estar seguro.', 'Recelar.'], thetaValue: 0.0),
      VocabularyItem(word: 'rincón', frequency: WordFrequency.medium, twoPointAnswers: ['Ángulo entrante que se forma en el encuentro de dos paredes o superficies.', 'Lugar apartado, escondido o poco visible de un espacio.', 'Sitio pequeño y retirado donde alguien se recoge o guarda algo.'], onePointAnswers: ['El ángulo de una habitación.', 'Un sitio escondido.', 'Donde se juntan dos paredes.', 'Lugar apartado.', 'Un espacio recogido.'], thetaValue: 0.0),
      VocabularyItem(word: 'tejado', frequency: WordFrequency.medium, twoPointAnswers: ['Cubierta superior de un edificio, generalmente inclinada y formada por tejas.', 'Parte más alta de una construcción que la protege de la lluvia y el sol.', 'Techo exterior de una casa colocado sobre el armazón del edificio.'], onePointAnswers: ['La parte de arriba de la casa.', 'Donde se ponen las tejas.', 'El techo de fuera.', 'Cubierta del edificio.', 'Lo que protege de la lluvia arriba.'], thetaValue: 0.0),
      VocabularyItem(word: 'murmurar', frequency: WordFrequency.medium, twoPointAnswers: ['Hablar en voz muy baja, de modo que apenas se oiga lo que se dice.', 'Hablar mal de alguien que está ausente, criticándolo en secreto.', 'Producir un sonido suave y continuo, como el del agua o el viento entre las hojas.'], onePointAnswers: ['Hablar muy bajito.', 'Criticar por detrás.', 'Cuchichear.', 'Decir cosas en secreto.', 'Hacer un ruido suave.'], thetaValue: 0.0),
      VocabularyItem(word: 'torpe', frequency: WordFrequency.medium, twoPointAnswers: ['Que se mueve con poca habilidad o destreza y choca o tropieza con facilidad.', 'Dicho de quien tarda en comprender o aprender algo, de entendimiento lento.', 'Que carece de gracia o soltura al hacer las cosas, actuando con dificultad.'], onePointAnswers: ['Que no tiene habilidad.', 'Que tropieza mucho.', 'Que aprende despacio.', 'Patoso.', 'Lo contrario de hábil.'], thetaValue: 0.0),
      VocabularyItem(word: 'rescatar', frequency: WordFrequency.medium, twoPointAnswers: ['Liberar a alguien o algo de un peligro, un encierro o una situación adversa.', 'Recuperar algo que se había perdido, abandonado u olvidado.', 'Salvar a una persona que está en una situación de riesgo o apuro.'], onePointAnswers: ['Salvar a alguien.', 'Sacar de un peligro.', 'Recuperar lo perdido.', 'Liberar a un atrapado.', 'Poner a salvo.'], thetaValue: 0.0),
      VocabularyItem(word: 'abundante', frequency: WordFrequency.medium, twoPointAnswers: ['Que existe en gran cantidad o número, más de lo necesario.', 'Dicho de algo que se da copiosamente o en exceso.', 'Que hay mucho de ello, de forma que sobra o satisface con creces.'], onePointAnswers: ['Que hay mucho.', 'En gran cantidad.', 'De sobra.', 'Copioso, numeroso.', 'Lo contrario de escaso.'], thetaValue: 0.0),
      VocabularyItem(word: 'regañar', frequency: WordFrequency.medium, twoPointAnswers: ['Reprender a alguien por algo que ha hecho mal, mostrándole disgusto o enfado.', 'Llamar la atención a una persona con severidad para corregir su conducta.', 'Reñir o enfadarse con alguien echándole en cara una falta.'], onePointAnswers: ['Echar la bronca.', 'Reñir a alguien.', 'Llamar la atención con enfado.', 'Reprender.', 'Decirle que se ha portado mal.'], thetaValue: 0.0),
      VocabularyItem(word: 'humilde', frequency: WordFrequency.medium, twoPointAnswers: ['Que no presume de sus méritos ni se cree superior a los demás.', 'Dicho de una persona de condición social modesta o de pocos recursos.', 'Que muestra sencillez y falta de altanería en su trato o en su modo de vivir.'], onePointAnswers: ['Que no es presumido.', 'Sencillo, modesto.', 'De pocos recursos.', 'Sin orgullo.', 'Lo contrario de soberbio.'], thetaValue: 0.0),
      VocabularyItem(word: 'tropezar', frequency: WordFrequency.medium, twoPointAnswers: ['Dar con los pies en un obstáculo al andar, perdiendo el equilibrio.', 'Encontrar de manera casual a una persona o cosa que no se buscaba.', 'Cometer un error o una falta al obrar, equivocándose en algo.'], onePointAnswers: ['Dar un traspié.', 'Casi caerse al andar.', 'Chocar con algo con el pie.', 'Encontrarse algo por casualidad.', 'Equivocarse.'], thetaValue: 0.0),
      VocabularyItem(word: 'ahorrar', frequency: WordFrequency.medium, twoPointAnswers: ['Guardar parte del dinero del que se dispone en lugar de gastarlo.', 'Evitar o reducir un gasto, un esfuerzo o un consumo innecesario.', 'Reservar algo para usarlo más adelante, no gastándolo ahora.'], onePointAnswers: ['Guardar dinero.', 'No gastar todo.', 'Reducir gastos.', 'Reservar para luego.', 'Lo contrario de derrochar.'], thetaValue: 0.0),
      VocabularyItem(word: 'desafiar', frequency: WordFrequency.medium, twoPointAnswers: ['Retar a alguien a una competición, una pelea o un enfrentamiento.', 'Enfrentarse con decisión a un peligro, una dificultad o una autoridad sin temor.', 'Provocar a una persona invitándola a medirse o a demostrar lo que es capaz de hacer.'], onePointAnswers: ['Retar a alguien.', 'Enfrentarse a algo sin miedo.', 'Plantar cara.', 'Provocar a otro.', 'Hacer frente a un peligro.'], thetaValue: 0.0),
    ],
    // low (14 items)
    [
      VocabularyItem(word: 'efímero', frequency: WordFrequency.low, twoPointAnswers: ['Que dura un periodo de tiempo muy breve y desaparece con rapidez.', 'Dicho de algo pasajero, de corta duración o que se desvanece pronto.', 'Que existe solo durante un instante o un plazo muy limitado antes de extinguirse.'], onePointAnswers: ['Que dura poco.', 'Pasajero, fugaz.', 'Breve en el tiempo.', 'Como una flor que se marchita en un día.', 'Que no permanece.'], thetaValue: 1.0),
      VocabularyItem(word: 'perenne', frequency: WordFrequency.low, twoPointAnswers: ['Que dura siempre o permanece de manera continua a lo largo del tiempo.', 'Dicho de una planta que vive más de dos años y conserva su follaje todo el año.', 'Que se mantiene sin interrupción ni cese, de forma constante y duradera.'], onePointAnswers: ['Que no se acaba.', 'Constante, permanente.', 'Que dura mucho.', 'Como un árbol de hoja siempre verde.', 'Continuo a lo largo del año.'], thetaValue: 1.0),
      VocabularyItem(word: 'perspicaz', frequency: WordFrequency.low, twoPointAnswers: ['Que percibe o comprende con agudeza y rapidez aquello que a otros se les escapa.', 'Dicho de la persona dotada de gran penetración de ingenio para captar detalles sutiles.', 'Que muestra una inteligencia aguda capaz de advertir lo que está oculto o disimulado.'], onePointAnswers: ['Muy listo y observador.', 'Agudo de mente.', 'Que se da cuenta de todo.', 'Sagaz, penetrante.', 'Que entiende las cosas enseguida.'], thetaValue: 1.0),
      VocabularyItem(word: 'indolente', frequency: WordFrequency.low, twoPointAnswers: ['Que no se esfuerza ni se afana en nada por falta de interés o de energía.', 'Dicho de quien actúa con dejadez, pereza y total despreocupación.', 'Que muestra indiferencia y flojedad, sin ganas de trabajar ni de actuar.'], onePointAnswers: ['Perezoso, vago.', 'Que no tiene ganas de nada.', 'Apático, sin energía.', 'Que lo deja todo para después.', 'Despreocupado y flojo.'], thetaValue: 1.0),
      VocabularyItem(word: 'menguar', frequency: WordFrequency.low, twoPointAnswers: ['Disminuir o reducirse algo en tamaño, cantidad o intensidad.', 'Ir haciéndose más pequeño o más escaso de forma progresiva.', 'Dicho de la Luna, presentar cada noche una porción iluminada menor.'], onePointAnswers: ['Hacerse más pequeño.', 'Reducirse, decrecer.', 'Bajar la cantidad.', 'Lo contrario de crecer.', 'Disminuir poco a poco.'], thetaValue: 1.0),
      VocabularyItem(word: 'hosco', frequency: WordFrequency.low, twoPointAnswers: ['Dicho de una persona de trato áspero, poco sociable y de gesto adusto.', 'Que se muestra antipático, ceñudo y de carácter intratable.', 'Que tiene un aspecto sombrío y desabrido, sin amabilidad alguna.'], onePointAnswers: ['Antipático y seco.', 'De mal humor.', 'Poco amable.', 'Arisco, huraño.', 'Que no sonríe nunca.'], thetaValue: 1.0),
      VocabularyItem(word: 'vetusto', frequency: WordFrequency.low, twoPointAnswers: ['Sumamente viejo y deteriorado por el paso de mucho tiempo.', 'Dicho de algo muy antiguo, anticuado y que muestra los estragos de los años.', 'Que es de una edad muy avanzada o de épocas remotas y caducas.'], onePointAnswers: ['Muy viejo.', 'Antiguo y gastado.', 'Que tiene muchos años.', 'Como un castillo en ruinas.', 'Anticuado.'], thetaValue: 1.0),
      VocabularyItem(word: 'exiguo', frequency: WordFrequency.low, twoPointAnswers: ['Que resulta insuficiente o muy escaso para lo que se necesita.', 'Dicho de una cantidad tan pequeña que apenas alcanza o satisface.', 'Que es reducido y de poca entidad o consideración.'], onePointAnswers: ['Muy poco, escaso.', 'Insuficiente.', 'Pequeño en cantidad.', 'Un sueldo muy bajo, casi nada.', 'Reducido, mínimo.'], thetaValue: 1.0),
      VocabularyItem(word: 'conciliar', frequency: WordFrequency.low, twoPointAnswers: ['Poner de acuerdo a personas o posturas que estaban enfrentadas o en disputa.', 'Hacer compatibles entre sí dos cosas que parecían opuestas o difíciles de unir.', 'Lograr o atraer hacia uno algo, como el sueño o la simpatía de alguien.'], onePointAnswers: ['Poner de acuerdo.', 'Armonizar posturas opuestas.', 'Hacer las paces entre dos.', 'Combinar trabajo y familia.', 'Lograr la concordia.'], thetaValue: 1.0),
      VocabularyItem(word: 'ahínco', frequency: WordFrequency.low, twoPointAnswers: ['Empeño grande y esfuerzo intenso con que se hace o se persigue algo.', 'Tesón y diligencia decidida puesta en una actividad o propósito.', 'Vehemencia y aplicación con que alguien se dedica a una tarea.'], onePointAnswers: ['Mucho empeño.', 'Con muchas ganas y esfuerzo.', 'Tesón, dedicación.', 'Trabajar sin descanso ni parar.', 'Insistencia, afán.'], thetaValue: 1.0),
      VocabularyItem(word: 'rebatir', frequency: WordFrequency.low, twoPointAnswers: ['Refutar con razones o argumentos lo que otro afirma o sostiene.', 'Oponerse a una idea o afirmación demostrando que es errónea o infundada.', 'Contradecir y desmontar los argumentos de una opinión contraria.'], onePointAnswers: ['Contradecir con argumentos.', 'Refutar.', 'Demostrar que algo es falso.', 'Llevar la contraria con razones.', 'Rechazar una idea.'], thetaValue: 1.0),
      VocabularyItem(word: 'soslayar', frequency: WordFrequency.low, twoPointAnswers: ['Esquivar o evitar una dificultad pasando de largo o sin afrontarla de frente.', 'Eludir un asunto delicado dejándolo a un lado en lugar de abordarlo.', 'Pasar por encima de un obstáculo o problema rodeándolo o ladeándolo.'], onePointAnswers: ['Evitar una dificultad.', 'Esquivar un problema.', 'Dejar de lado un tema.', 'Pasar de puntillas por un asunto.', 'Rehuir, sortear.'], thetaValue: 1.0),
      VocabularyItem(word: 'sosegado', frequency: WordFrequency.low, twoPointAnswers: ['Que está tranquilo, sereno y libre de agitación o inquietud.', 'Dicho de la persona o el ambiente que transmite calma y reposo.', 'Que actúa o transcurre con quietud y sin sobresaltos.'], onePointAnswers: ['Tranquilo, calmado.', 'Sereno.', 'Sin nervios ni prisa.', 'Que da paz.', 'Apacible.'], thetaValue: 1.0),
      VocabularyItem(word: 'recóndito', frequency: WordFrequency.low, twoPointAnswers: ['Que está muy escondido, oculto o situado en un lugar apartado y de difícil acceso.', 'Dicho de aquello que resulta reservado, secreto o profundo y no se muestra a la vista.', 'Que se halla en lo más íntimo o profundo, lejos de lo evidente.'], onePointAnswers: ['Muy escondido.', 'Oculto, secreto.', 'En lo más profundo.', 'Un rincón muy escondido.', 'Apartado y difícil de hallar.'], thetaValue: 1.0),
    ],
    // veryLow (14 items)
    [
      VocabularyItem(word: 'inefable', frequency: WordFrequency.veryLow, twoPointAnswers: ['Que no puede expresarse o describirse con palabras por su intensidad o sutileza.', 'Dicho de un sentimiento o experiencia: tan elevado o profundo que resulta imposible explicarlo mediante el lenguaje.', 'Que excede toda capacidad de ser nombrado o dicho.', 'Cuya grandeza o belleza supera lo que las palabras alcanzan a comunicar.'], onePointAnswers: ['Que no se puede decir con palabras.', 'Indescriptible.', 'Algo tan bonito que no sabes cómo expresarlo.', 'Imposible de explicar.', 'Inexpresable.'], thetaValue: 2.0),
      VocabularyItem(word: 'lóbrego', frequency: WordFrequency.veryLow, twoPointAnswers: ['Oscuro, sombrío y carente de luz, que produce tristeza o temor.', 'Dicho de un lugar: tenebroso y triste por su falta de claridad.', 'Que está envuelto en penumbra y transmite una sensación melancólica o lúgubre.', 'Tenebroso y desangelado, propio de un ambiente sin luz ni alegría.'], onePointAnswers: ['Oscuro y triste.', 'Sombrío.', 'Un sótano sin ventanas, por ejemplo.', 'Tenebroso.', 'Que da miedo por lo oscuro.', 'Lúgubre.'], thetaValue: 2.0),
      VocabularyItem(word: 'fruslería', frequency: WordFrequency.veryLow, twoPointAnswers: ['Cosa de muy poco valor o importancia que no merece atención.', 'Asunto trivial e insignificante por el que no vale la pena preocuparse.', 'Bagatela o nadería sin sustancia ni relevancia alguna.', 'Dicho o hecho de escasa monta que carece de mérito o interés.'], onePointAnswers: ['Cosa sin importancia.', 'Una tontería.', 'Algo que no vale nada.', 'Una nadería.', 'Un detalle insignificante.'], thetaValue: 2.0),
      VocabularyItem(word: 'fárrago', frequency: WordFrequency.veryLow, twoPointAnswers: ['Conjunto de cosas o ideas desordenadas, mezcladas y confusas.', 'Amontonamiento de elementos superfluos que estorba o resulta inútil.', 'Mezcla revuelta y excesiva de cosas heterogéneas y sin orden.', 'Acumulación caótica de detalles o asuntos que dificulta la claridad.'], onePointAnswers: ['Lío de cosas mezcladas.', 'Desorden.', 'Un montón de datos sin orden.', 'Cosas amontonadas sin sentido.', 'Mezcolanza confusa.'], thetaValue: 2.0),
      VocabularyItem(word: 'ataraxia', frequency: WordFrequency.veryLow, twoPointAnswers: ['Estado de tranquilidad del ánimo, libre de inquietudes y perturbaciones.', 'Serenidad imperturbable que algunas filosofías antiguas proponían como ideal de vida.', 'Calma profunda del espíritu en la que no afectan las pasiones ni los temores.', 'Disposición de sosiego interior en que la persona permanece impasible ante lo externo.'], onePointAnswers: ['Calma absoluta.', 'Tranquilidad del ánimo.', 'Serenidad total.', 'No alterarse por nada.', 'Paz interior.', 'Estado de los filósofos estoicos.'], thetaValue: 2.0),
      VocabularyItem(word: 'pusilánime', frequency: WordFrequency.veryLow, twoPointAnswers: ['Que carece de valor o de ánimo para afrontar dificultades o riesgos.', 'Dicho de una persona: temerosa y de poco coraje ante las situaciones adversas.', 'Falto de firmeza y de decisión, que se acobarda con facilidad.', 'De ánimo apocado que rehúye cualquier empresa que entrañe esfuerzo o peligro.'], onePointAnswers: ['Cobarde.', 'Sin valor.', 'Que se asusta con todo.', 'Apocado.', 'Persona miedosa y sin ánimo.', 'Temeroso.'], thetaValue: 2.0),
      VocabularyItem(word: 'preterir', frequency: WordFrequency.veryLow, twoPointAnswers: ['Omitir o no tener en cuenta a alguien o algo que debería considerarse.', 'Dejar de lado o postergar a una persona en aquello que le correspondería.', 'Hacer caso omiso de alguien, excluyéndolo de un derecho o de una mención debida.', 'Pasar por alto deliberadamente a quien tendría que haber sido tomado en cuenta.'], onePointAnswers: ['Omitir a alguien.', 'Dejar de lado.', 'No mencionar a quien correspondía.', 'Excluir.', 'Postergar a una persona.'], thetaValue: 2.0),
      VocabularyItem(word: 'epígono', frequency: WordFrequency.veryLow, twoPointAnswers: ['Persona que sigue las huellas o las ideas de otra anterior, sobre todo en arte o pensamiento.', 'Continuador de una escuela, estilo o generación que prolonga la obra de sus predecesores.', 'Quien pertenece a una época posterior y reproduce o imita a los maestros que le precedieron.', 'Discípulo o seguidor tardío de una corriente, sin aportar verdadera originalidad.'], onePointAnswers: ['Seguidor de otro.', 'Imitador de un maestro.', 'El que continúa una escuela.', 'Discípulo tardío.', 'Heredero de un estilo.'], thetaValue: 2.0),
      VocabularyItem(word: 'veleidad', frequency: WordFrequency.veryLow, twoPointAnswers: ['Inconstancia o ligereza en los propósitos, los gustos o los afectos.', 'Capricho o antojo pasajero al que falta firmeza y constancia.', 'Voluntad poco resuelta que cambia con facilidad de una cosa a otra.', 'Deseo vago y mudable que no llega a convertirse en decisión firme.'], onePointAnswers: ['Capricho pasajero.', 'Inconstancia.', 'Cambiar de gustos a menudo.', 'Antojo.', 'Voluntad que no dura.', 'Ligereza de carácter.'], thetaValue: 2.0),
      VocabularyItem(word: 'conspicuo', frequency: WordFrequency.veryLow, twoPointAnswers: ['Ilustre, notable y sobresaliente entre los de su clase.', 'Que destaca por su importancia, su dignidad o su mérito reconocido.', 'Dicho de una persona: distinguida y de gran relieve en su ámbito.', 'Que llama la atención por ser eminente o visible por encima de los demás.'], onePointAnswers: ['Ilustre.', 'Destacado.', 'Persona muy importante.', 'Eminente.', 'Que sobresale.', 'Notable.'], thetaValue: 2.0),
      VocabularyItem(word: 'zaherir', frequency: WordFrequency.veryLow, twoPointAnswers: ['Decir o hacer algo para mortificar o humillar a una persona.', 'Reprender a alguien con palabras hirientes que causan dolor o vergüenza.', 'Maltratar de palabra censurando con dureza y mala intención.', 'Herir el amor propio de alguien mediante reproches o burlas mordaces.'], onePointAnswers: ['Herir con palabras.', 'Humillar a alguien.', 'Reprochar con dureza.', 'Decir cosas que duelen.', 'Burlarse hiriendo.', 'Mortificar.'], thetaValue: 2.0),
      VocabularyItem(word: 'conculcar', frequency: WordFrequency.veryLow, twoPointAnswers: ['Quebrantar o vulnerar una ley, un derecho o un principio.', 'Infringir gravemente una norma o un deber, pasando por encima de él.', 'Pisotear lo que debería respetarse, como un derecho o una obligación.', 'Atropellar o transgredir aquello que la ley o la moral mandan acatar.'], onePointAnswers: ['Quebrantar una ley.', 'Vulnerar un derecho.', 'Pisotear una norma.', 'Infringir.', 'Saltarse lo que debe respetarse.'], thetaValue: 2.0),
      VocabularyItem(word: 'denodado', frequency: WordFrequency.veryLow, twoPointAnswers: ['Que actúa con valentía y empeño decidido, sin retroceder ante las dificultades.', 'Esforzado e intrépido, que se entrega con ánimo resuelto a una tarea ardua.', 'Dicho del esfuerzo o de la persona: lleno de brío, audacia y constancia.', 'Que muestra arrojo y tesón firmes frente al riesgo o al trabajo.'], onePointAnswers: ['Valiente.', 'Esforzado.', 'Que se entrega con empeño.', 'Intrépido.', 'Que no se rinde.', 'Audaz y tenaz.'], thetaValue: 2.0),
      VocabularyItem(word: 'arrebol', frequency: WordFrequency.veryLow, twoPointAnswers: ['Color rojizo que tiñe las nubes iluminadas por los rayos del sol al amanecer o al atardecer.', 'Rubor o tono encendido que adquiere el cielo cuando el sol está bajo en el horizonte.', 'Encendido matiz rojo o rosado que toma el rostro o las nubes.', 'Tono carmesí de las nubes alumbradas oblicuamente por la luz solar.'], onePointAnswers: ['El rojo del cielo al atardecer.', 'Color rojizo de las nubes.', 'Rubor en las mejillas.', 'Tono rosado del horizonte.', 'El cielo encendido del ocaso.'], thetaValue: 2.0),
    ],
  ];
}
