-- OBSOLÈTE — le worker referral utilise désormais Cloudflare KV (binding
-- REFERRAL_KV dans wrangler.toml), plus Supabase. Aucun schéma SQL à exécuter.
--
-- Le token Cloudflare disponible est limité à Workers + Pages (pas de droit
-- D1/Supabase), et l'app Mentality est déjà 100 % Cloudflare (Workers + R2) :
-- KV évite toute dépendance et tout secret externe.
--
-- Modèle de clés KV (voir index.js) :
--   progress:<account>        état des paliers du parrain (JSON)
--   code:<referralCode>       compte propriétaire du code (unicité + resolve)
--   referee:<account>         referrerCode validé (écrit une fois : 1 filleul = 1 parrain)
--   ref:<referrerCode>:<acct> filleul ayant terminé son test (comptage)
--
-- Consulter les pseudos Instagram soumis (contrôle manuel) :
--   wrangler kv key list  --binding REFERRAL_KV | grep '^progress:'
--   wrangler kv key get   --binding REFERRAL_KV "progress:<account>"
-- Invalider un abonnement non tenu (re-verrouille) : remettre instagramVerified
-- à false dans le JSON puis wrangler kv key put.
