-- OBSOLÈTE — le worker referral utilise désormais Cloudflare KV (binding
-- REFERRAL_KV dans wrangler.toml), plus Supabase. Aucun schéma SQL à exécuter.
--
-- Le token Cloudflare disponible est limité à Workers + Pages (pas de droit
-- D1/Supabase), et l'app Mentality est déjà 100 % Cloudflare (Workers + R2) :
-- KV évite toute dépendance et tout secret externe.
--
-- Modèle de clés KV (voir index.js) :
--   progress:<account>        état des paliers du parrain (JSON ; champ
--                             firstSeenVia depuis le LOT 0 anti-faux-test)
--   code:<referralCode>       compte propriétaire du code (unicité + resolve)
--   referee:<account>         lien filleul→parrain, écrit une fois (1 filleul =
--                             1 parrain). Neuf : JSON {code, at} ; legacy :
--                             referrerCode brut (cf. parseRefereeLink)
--   ref:<referrerCode>:<acct> filleul ayant terminé son test (comptage)
--   completed:<account>       preuve de complétion du test (première fois gagne)
--
-- Inspecter l'état d'un compte (stage, stage3StartedAt, unlockedAt) :
--   wrangler kv key list  --binding REFERRAL_KV | grep '^progress:'
--   wrangler kv key get   --binding REFERRAL_KV "progress:<account>"
--
-- Il n'existe PLUS de levier de re-verrouillage manuel : le champ
-- instagramVerified a disparu avec l'étape Instagram. Le palier 3 est un simple
-- délai (UNLOCK_DELAY_MINUTES), personne n'est « vérifié ».
-- Purge RGPD des champs Instagram des lignes déjà en production :
--   CF_API_TOKEN=… CF_ACCOUNT_ID=… node scripts/purge-instagram.js          # dry-run
--   CF_API_TOKEN=… CF_ACCOUNT_ID=… node scripts/purge-instagram.js --apply
