/// Banque de paires du sous-test Similitudes — en_GB (GÉNÉRÉ par IA, vérifié). 4 niveaux d'abstraction. NE PAS éditer à la main.
library;

import 'similarities_generator.dart';

List<List<SimilarityItem>> buildBritishSimilarityBanks() {
  return [
    // concrete (12 paires)
    [
      SimilarityItem(word1: 'orange', word2: 'banana', level: AbstractionLevel.concrete, twoPointAnswers: ['They are both fruit.', 'Both are types of fruit.', 'Both belong to the fruit category.'], onePointAnswers: ['You can eat both of them.', 'Both have a skin or peel.', 'Both grow on plants.', 'Both are sweet.', 'Both are found in a fruit bowl.'], thetaValue: -1.5),
      SimilarityItem(word1: 'dog', word2: 'cat', level: AbstractionLevel.concrete, twoPointAnswers: ['They are both pets.', 'Both are domestic animals kept as pets.', 'Both are animals people keep in the home.'], onePointAnswers: ['Both have four legs.', 'Both have fur.', 'Both make sounds.', 'Both need feeding every day.', 'Both are kept in the house.'], thetaValue: -1.5),
      SimilarityItem(word1: 'rose', word2: 'daisy', level: AbstractionLevel.concrete, twoPointAnswers: ['They are both flowers.', 'Both are types of flower.', 'Both are flowering plants.'], onePointAnswers: ['Both grow in gardens.', 'Both have petals.', 'Both can be used in a bunch or bouquet.', 'Both need water and sunlight.', 'Both can be given as gifts.'], thetaValue: -1.5),
      SimilarityItem(word1: 'hammer', word2: 'screwdriver', level: AbstractionLevel.concrete, twoPointAnswers: ['They are both tools.', 'Both are hand tools.', 'Both are tools used for DIY or repair work.'], onePointAnswers: ['Both are used for fixing things.', 'Both are held in the hand.', 'Both are kept in a toolbox.', 'Both are made partly of metal.', 'Both are used by builders and tradespeople.'], thetaValue: -1.5),
      SimilarityItem(word1: 'bus', word2: 'train', level: AbstractionLevel.concrete, twoPointAnswers: ['They are both forms of public transport.', 'Both are vehicles used to carry passengers.', 'Both are means of public transportation.'], onePointAnswers: ['Both carry many people at once.', 'Both run on a fixed route or timetable.', 'Both require a ticket.', 'Both are used for commuting.', 'Both have seats for passengers.'], thetaValue: -1.5),
      SimilarityItem(word1: 'table', word2: 'chair', level: AbstractionLevel.concrete, twoPointAnswers: ['They are both pieces of furniture.', 'Both are items of furniture.', 'Both are types of household furniture.'], onePointAnswers: ['Both are found in a dining room.', 'Both are often made of wood.', 'Both have legs.', 'Both are bought from a furniture shop.', 'Both are used at mealtimes.'], thetaValue: -1.5),
      SimilarityItem(word1: 'shirt', word2: 'trousers', level: AbstractionLevel.concrete, twoPointAnswers: ['They are both items of clothing.', 'Both are articles of clothing worn on the body.', 'Both are garments.'], onePointAnswers: ['Both are made from fabric.', 'Both can be bought in a shop.', 'Both need to be washed.', 'Both can be worn by men or women.', 'Both come in different colours and sizes.'], thetaValue: -1.5),
      SimilarityItem(word1: 'piano', word2: 'guitar', level: AbstractionLevel.concrete, twoPointAnswers: ['They are both musical instruments.', 'Both are types of musical instrument.', 'Both are instruments used to make music.'], onePointAnswers: ['Both produce sound when played.', 'Both are used in concerts.', 'Both can be used to play songs.', 'Both require practice to learn.', 'Both can accompany a singer.'], thetaValue: -1.5),
      SimilarityItem(word1: 'carrot', word2: 'potato', level: AbstractionLevel.concrete, twoPointAnswers: ['They are both vegetables.', 'Both are types of vegetable.', 'Both are common vegetables eaten as food.'], onePointAnswers: ['Both grow in the ground.', 'Both are used in cooking.', 'Both can be boiled or roasted.', 'Both are sold in supermarkets.', 'Both are used in stews and soups.'], thetaValue: -1.5),
      SimilarityItem(word1: 'robin', word2: 'sparrow', level: AbstractionLevel.concrete, twoPointAnswers: ['They are both birds.', 'Both are types of bird.', 'Both are common garden birds.'], onePointAnswers: ['Both have feathers and wings.', 'Both can fly.', 'Both lay eggs.', 'Both are seen in British gardens.', 'Both build nests.'], thetaValue: -1.5),
      SimilarityItem(word1: 'cup', word2: 'bowl', level: AbstractionLevel.concrete, twoPointAnswers: ['They are both items of crockery.', 'Both are pieces of crockery used at mealtimes.', 'Both are types of tableware.'], onePointAnswers: ['Both hold food or drink.', 'Both are made from ceramic or china.', 'Both are washed up after use.', 'Both are found in a kitchen cupboard.', 'Both can be used as containers.'], thetaValue: -1.5),
      SimilarityItem(word1: 'penny', word2: 'pound', level: AbstractionLevel.concrete, twoPointAnswers: ['They are both coins.', 'Both are types of British coin.', 'Both are forms of money used in Britain.'], onePointAnswers: ['Both are made of metal.', 'Both are round.', 'Both are used to pay for things.', 'Both can be kept in a purse or wallet.', 'Both are legal tender.'], thetaValue: -1.5),
    ],
    // functional (14 paires)
    [
      SimilarityItem(word1: 'boat', word2: 'aeroplane', level: AbstractionLevel.functional, twoPointAnswers: ['they are means of transport', 'they are vehicles used to travel from one place to another', 'they are modes of transportation', 'they are used to carry passengers or goods'], onePointAnswers: ['both can carry people', 'both have engines', 'both are used for long journeys', 'both require a trained operator', 'both can be used to travel abroad'], thetaValue: -0.5),
      SimilarityItem(word1: 'knife', word2: 'scissors', level: AbstractionLevel.functional, twoPointAnswers: ['they are cutting implements', 'they are tools used for cutting', 'they are sharp instruments used to cut things', 'they are cutting tools'], onePointAnswers: ['both have blades', 'both are sharp', 'both are made of metal', 'both are used in the kitchen', 'both can be dangerous if misused'], thetaValue: -0.5),
      SimilarityItem(word1: 'torch', word2: 'candle', level: AbstractionLevel.functional, twoPointAnswers: ['they are sources of light', 'they are used to provide illumination', 'they are devices that produce light', 'they are used to light up dark spaces'], onePointAnswers: ['both are portable', 'both are useful when there is no electricity', 'both can be carried by hand', 'both are useful during a power cut', 'both produce a visible glow'], thetaValue: -0.5),
      SimilarityItem(word1: 'telephone', word2: 'letter', level: AbstractionLevel.functional, twoPointAnswers: ['they are means of communication', 'they are ways of sending or receiving a message', 'they are methods used to communicate with others', 'they are used to pass information between people'], onePointAnswers: ['both can be used to contact someone far away', 'both carry words or messages', 'both are used to keep in touch', 'both can be personal or formal', 'both involve sending information'], thetaValue: -0.5),
      SimilarityItem(word1: 'broom', word2: 'vacuum cleaner', level: AbstractionLevel.functional, twoPointAnswers: ['they are used for cleaning floors', 'they are cleaning implements', 'they are tools used to remove dirt and dust from floors', 'they are devices used for household cleaning'], onePointAnswers: ['both are used in the home', 'both remove dust and debris', 'both are moved along the floor', 'both are cleaning tools', 'both are found in most households'], thetaValue: -0.5),
      SimilarityItem(word1: 'bridge', word2: 'ladder', level: AbstractionLevel.functional, twoPointAnswers: ['they are structures used to help people get to somewhere otherwise unreachable', 'they are structures that allow people to overcome a physical obstacle', 'they are used to gain access to a place that would otherwise be blocked or out of reach', 'they are structures that enable movement across or up an obstacle'], onePointAnswers: ['both are made of sturdy material', 'both require care to use safely', 'both allow access to a place', 'both are built structures', 'both help people move from one point to another'], thetaValue: -0.5),
      SimilarityItem(word1: 'spectacles', word2: 'hearing aid', level: AbstractionLevel.functional, twoPointAnswers: ['they are devices that correct or compensate for a sensory impairment', 'they are aids used to improve a person\'s ability to perceive the world', 'they are assistive devices for the senses', 'they are medical aids that help people with a disability'], onePointAnswers: ['both are worn on the head', 'both are medical devices', 'both help people with a disability', 'both are fitted or prescribed by a specialist', 'both improve quality of life'], thetaValue: -0.5),
      SimilarityItem(word1: 'pen', word2: 'typewriter', level: AbstractionLevel.functional, twoPointAnswers: ['they are used for writing', 'they are tools for producing written text', 'they are instruments used to record words', 'they are writing implements or devices'], onePointAnswers: ['both produce text on paper', 'both require some effort to operate', 'both are used in offices', 'both can be used to write letters', 'both leave marks on paper'], thetaValue: -0.5),
      SimilarityItem(word1: 'map', word2: 'compass', level: AbstractionLevel.functional, twoPointAnswers: ['they are used for navigation', 'they are tools that help people find their way', 'they are navigation aids', 'they are used to determine direction or location'], onePointAnswers: ['both are used by walkers and explorers', 'both help you avoid getting lost', 'both are useful outdoors', 'both are used in orienteering', 'both are traditional navigation tools'], thetaValue: -0.5),
      SimilarityItem(word1: 'umbrella', word2: 'raincoat', level: AbstractionLevel.functional, twoPointAnswers: ['they are used to protect a person from the rain', 'they are items of weather protection', 'they are used to keep dry in wet weather', 'they are protective items carried or worn in the rain'], onePointAnswers: ['both are used in bad weather', 'both keep you dry', 'both are waterproof', 'both are particularly useful in Britain', 'both are carried or worn outdoors'], thetaValue: -0.5),
      SimilarityItem(word1: 'thermometer', word2: 'scales', level: AbstractionLevel.functional, twoPointAnswers: ['they are measuring instruments', 'they are devices used to take a precise measurement', 'they are tools used to quantify something accurately', 'they are instruments used to record a physical quantity'], onePointAnswers: ['both give a reading', 'both use numbers to show a result', 'both are used in medicine or science', 'both need to be read carefully to get an accurate result', 'both are used to monitor health'], thetaValue: -0.5),
      SimilarityItem(word1: 'fridge', word2: 'freezer', level: AbstractionLevel.functional, twoPointAnswers: ['they are used to preserve food', 'they are appliances used to keep food fresh', 'they are kitchen devices used to store food at low temperatures', 'they are used to stop food from going off'], onePointAnswers: ['both use electricity', 'both are found in kitchens', 'both keep food cold', 'both have a door that seals shut', 'both are used to store perishable goods'], thetaValue: -0.5),
      SimilarityItem(word1: 'alarm clock', word2: 'calendar', level: AbstractionLevel.functional, twoPointAnswers: ['they are used to help people manage and organise their time', 'they are tools for planning and keeping track of time', 'they are used to remind or alert people about time', 'they are timekeeping aids that help people stay organised'], onePointAnswers: ['both have numbers on them', 'both are found in homes and offices', 'both help people plan their day', 'both display time-related information', 'both are used for scheduling'], thetaValue: -0.5),
      SimilarityItem(word1: 'lock', word2: 'safe', level: AbstractionLevel.functional, twoPointAnswers: ['they are used to keep things secure', 'they are security devices used to protect valuables', 'they are used to prevent unauthorised access', 'they are devices used to safeguard belongings'], onePointAnswers: ['both are made of metal', 'both require a key or combination to open', 'both are used to protect property', 'both are found in homes and offices', 'both are used to deter theft'], thetaValue: -0.5),
    ],
    // categorical (16 paires)
    [
      SimilarityItem(word1: 'anger', word2: 'joy', level: AbstractionLevel.categorical, twoPointAnswers: ['They are both emotions.', 'Both are types of feeling or emotion.', 'They are both emotional states experienced by people.', 'Both belong to the category of human emotions.'], onePointAnswers: ['Both can be shown on your face.', 'Both can affect how you behave.', 'Both can be intense or mild.', 'Both pass with time.', 'Both can be triggered by other people.'], thetaValue: 0.5),
      SimilarityItem(word1: 'violin', word2: 'piano', level: AbstractionLevel.categorical, twoPointAnswers: ['They are both musical instruments.', 'Both are instruments used to make music.', 'They are both types of musical instrument.', 'Both belong to the category of musical instruments.'], onePointAnswers: ['Both are used in an orchestra.', 'Both are taught in music lessons.', 'Both can play classical music.', 'Both require practice to learn.', 'Both produce sound from vibrating parts.'], thetaValue: 0.5),
      SimilarityItem(word1: 'courage', word2: 'patience', level: AbstractionLevel.categorical, twoPointAnswers: ['They are both virtues.', 'Both are desirable qualities of character.', 'They are both moral virtues or personal strengths.', 'Both belong to the category of human virtues.'], onePointAnswers: ['Both are considered admirable in a person.', 'Both can be developed with effort.', 'Both help you cope with difficulties.', 'Both are praised in most cultures.', 'Both make life easier for yourself and others.'], thetaValue: 0.5),
      SimilarityItem(word1: 'democracy', word2: 'monarchy', level: AbstractionLevel.categorical, twoPointAnswers: ['They are both systems of government.', 'Both are forms of governance or political systems.', 'They are both ways of organising the running of a state or country.', 'Both are types of political system.'], onePointAnswers: ['Both involve leaders or rulers.', 'Both affect the people living under them.', 'Both have laws and rules.', 'Both have existed throughout history.', 'Both involve authority and power.'], thetaValue: 0.5),
      SimilarityItem(word1: 'novel', word2: 'biography', level: AbstractionLevel.categorical, twoPointAnswers: ['They are both types of book.', 'Both are forms of written literature.', 'They are both literary works published in book form.', 'Both belong to the category of books or written works.'], onePointAnswers: ['Both are sold in bookshops.', 'Both have an author.', 'Both are read for pleasure or information.', 'Both can be borrowed from a library.', 'Both take time to read from cover to cover.'], thetaValue: 0.5),
      SimilarityItem(word1: 'pessimism', word2: 'optimism', level: AbstractionLevel.categorical, twoPointAnswers: ['They are both attitudes or outlooks on life.', 'Both are ways of thinking about or perceiving the world.', 'They are both mental dispositions or philosophical stances.', 'Both are types of mindset or worldview.'], onePointAnswers: ['Both influence how you feel day to day.', 'Both can affect your decisions.', 'Both describe a person\'s general outlook.', 'Both are discussed in psychology.', 'Both can be changed with effort or therapy.'], thetaValue: 0.5),
      SimilarityItem(word1: 'lung', word2: 'kidney', level: AbstractionLevel.categorical, twoPointAnswers: ['They are both internal organs.', 'Both are organs in the human body.', 'They are both vital organs essential for life.', 'Both belong to the category of internal body organs.'], onePointAnswers: ['Both are inside the body.', 'Both can be affected by disease.', 'Both are studied in biology and medicine.', 'Both can sometimes be transplanted.', 'Both come in pairs in the human body.'], thetaValue: 0.5),
      SimilarityItem(word1: 'envy', word2: 'admiration', level: AbstractionLevel.categorical, twoPointAnswers: ['They are both attitudes directed towards other people.', 'Both are ways of responding to someone else\'s qualities or achievements.', 'They are both social emotions involving how you perceive others.', 'Both belong to the category of social or interpersonal emotions.'], onePointAnswers: ['Both arise when you notice something impressive in someone else.', 'Both can motivate a person to change.', 'Both involve making a comparison with others.', 'Both can affect your relationships.', 'Both are felt in everyday social situations.'], thetaValue: 0.5),
      SimilarityItem(word1: 'Buddhism', word2: 'Christianity', level: AbstractionLevel.categorical, twoPointAnswers: ['They are both religions.', 'Both are world religions or organised systems of belief.', 'They are both established religious faiths with followers worldwide.', 'Both are types of religious tradition.'], onePointAnswers: ['Both have places of worship.', 'Both involve spiritual practice.', 'Both have sacred texts.', 'Both offer guidance on how to live.', 'Both have rituals and ceremonies.'], thetaValue: 0.5),
      SimilarityItem(word1: 'drought', word2: 'flood', level: AbstractionLevel.categorical, twoPointAnswers: ['They are both natural disasters.', 'Both are types of extreme natural event or catastrophe.', 'They are both environmental phenomena that cause widespread harm.', 'Both belong to the category of natural disasters.'], onePointAnswers: ['Both can cause loss of life.', 'Both damage crops and farmland.', 'Both require emergency responses from authorities.', 'Both affect communities and infrastructure.', 'Both can be worsened by climate change.'], thetaValue: 0.5),
      SimilarityItem(word1: 'capitalism', word2: 'socialism', level: AbstractionLevel.categorical, twoPointAnswers: ['They are both economic systems.', 'Both are political and economic ideologies.', 'They are both ways of organising a society\'s economy.', 'Both belong to the category of economic or political systems.'], onePointAnswers: ['Both involve ideas about the distribution of wealth and resources.', 'Both have been adopted by different countries.', 'Both are debated by politicians and thinkers.', 'Both affect how people live and work.', 'Both are studied in economics and politics.'], thetaValue: 0.5),
      SimilarityItem(word1: 'grief', word2: 'loneliness', level: AbstractionLevel.categorical, twoPointAnswers: ['They are both forms of psychological suffering.', 'Both are types of painful inner experience.', 'They are both states of emotional distress.', 'Both belong to the category of negative emotional or psychological states.'], onePointAnswers: ['Both can affect your sleep and appetite.', 'Both may require support from others.', 'Both pass with time for most people.', 'Both can feel overwhelming.', 'Both are common human experiences.'], thetaValue: 0.5),
      SimilarityItem(word1: 'comedy', word2: 'tragedy', level: AbstractionLevel.categorical, twoPointAnswers: ['They are both dramatic genres.', 'Both are forms of theatre or dramatic literature.', 'They are both types of theatrical or literary genre.', 'Both belong to the category of dramatic genres.'], onePointAnswers: ['Both are performed on stage.', 'Both involve actors following a script.', 'Both aim to provoke a strong emotional response in the audience.', 'Both have ancient origins in Greek theatre.', 'Both are studied in drama and literature.'], thetaValue: 0.5),
      SimilarityItem(word1: 'algebra', word2: 'geometry', level: AbstractionLevel.categorical, twoPointAnswers: ['They are both branches of mathematics.', 'Both are areas of maths.', 'They are both mathematical disciplines.', 'Both belong to the category of mathematical fields.'], onePointAnswers: ['Both are taught at secondary school.', 'Both involve solving problems.', 'Both use symbols and formulas.', 'Both are part of the maths curriculum.', 'Both require logical thinking.'], thetaValue: 0.5),
      SimilarityItem(word1: 'opera', word2: 'ballet', level: AbstractionLevel.categorical, twoPointAnswers: ['They are both forms of performing art.', 'Both are types of classical performing arts.', 'They are both artistic disciplines performed on stage for an audience.', 'Both belong to the category of classical performing arts.'], onePointAnswers: ['Both are performed in theatres.', 'Both involve costumes and staging.', 'Both require years of training.', 'Both often involve orchestral music.', 'Both have a long tradition in European culture.'], thetaValue: 0.5),
      SimilarityItem(word1: 'iron', word2: 'copper', level: AbstractionLevel.categorical, twoPointAnswers: ['They are both metals.', 'Both are chemical elements classified as metals.', 'They are both naturally occurring metallic elements.', 'Both belong to the category of metals.'], onePointAnswers: ['Both are found in the earth.', 'Both conduct electricity.', 'Both are used in construction and manufacturing.', 'Both have been used by humans throughout history.', 'Both are hard and shiny when polished.'], thetaValue: 0.5),
    ],
    // abstract (12 paires)
    [
      SimilarityItem(word1: 'liberty', word2: 'justice', level: AbstractionLevel.abstract, twoPointAnswers: ['abstract ideals that underpin the moral foundations of a just society', 'fundamental principles of political and moral philosophy', 'normative values at the heart of human rights', 'universal moral aspirations by which societies judge themselves'], onePointAnswers: ['things people fight for', 'things associated with law and government', 'concepts taught in civics', 'things that can be denied or granted', 'ideals written into constitutions'], thetaValue: 1.5),
      SimilarityItem(word1: 'praise', word2: 'punishment', level: AbstractionLevel.abstract, twoPointAnswers: ['mechanisms for regulating and shaping behaviour', 'instruments of social and moral control', 'tools used to reinforce norms and enforce standards of conduct', 'means by which individuals and societies respond to and influence behaviour'], onePointAnswers: ['things a teacher might use', 'reactions to what someone has done', 'things parents use with children', 'they both affect how someone acts', 'responses to behaviour'], thetaValue: 1.5),
      SimilarityItem(word1: 'chaos', word2: 'order', level: AbstractionLevel.abstract, twoPointAnswers: ['opposing abstract principles that describe the organisation of systems', 'fundamental conceptual poles through which reality and society are interpreted', 'philosophical categories governing the structure — or lack of it — in any domain', 'antithetical conditions that define the spectrum between breakdown and stability'], onePointAnswers: ['things you can have in a room or a country', 'opposites that describe situations', 'words used in science and politics', 'states that can change into each other', 'things associated with how well something is run'], thetaValue: 1.5),
      SimilarityItem(word1: 'courage', word2: 'wisdom', level: AbstractionLevel.abstract, twoPointAnswers: ['classical virtues prized across cultures and philosophical traditions', 'moral and intellectual excellences of character', 'cardinal virtues in ethical philosophy defining what it is to live well', 'enduring standards of human excellence recognised across time and culture'], onePointAnswers: ['qualities admired in people', 'things you can develop over time', 'good personal traits', 'things associated with great leaders', 'qualities celebrated in stories and myths'], thetaValue: 1.5),
      SimilarityItem(word1: 'authority', word2: 'tradition', level: AbstractionLevel.abstract, twoPointAnswers: ['sources of legitimacy upon which social order is grounded', 'abstract mechanisms by which societies maintain continuity and compliance across generations', 'forces that constrain individual behaviour by appeal to something beyond personal preference', 'foundations upon which norms, rules, and institutions are justified'], onePointAnswers: ['things that tell people what to do', 'things passed down or established over time', 'concepts associated with conservatism', 'they can both be challenged or questioned', 'things that give structure to society'], thetaValue: 1.5),
      SimilarityItem(word1: 'censorship', word2: 'propaganda', level: AbstractionLevel.abstract, twoPointAnswers: ['instruments of ideological control used to manage what people think and know', 'mechanisms by which those in power manipulate the flow and content of information', 'abstract tools of epistemic dominance through which belief and consent are engineered', 'means of constraining or directing public thought in the service of power'], onePointAnswers: ['things associated with authoritarian regimes', 'things involving the media', 'ways of controlling what people hear', 'things that can be used by governments', 'they both restrict or distort information'], thetaValue: 1.5),
      SimilarityItem(word1: 'revolution', word2: 'reform', level: AbstractionLevel.abstract, twoPointAnswers: ['abstract modes of social and political transformation', 'conceptually distinct strategies for changing the structures of society', 'responses to injustice or dysfunction that operate at the level of systems and institutions', 'philosophical categories describing how societies change in degree or in kind'], onePointAnswers: ['things associated with political change', 'things that can improve a country', 'things studied in history', 'ways of challenging the status quo', 'things that can be violent or peaceful'], thetaValue: 1.5),
      SimilarityItem(word1: 'memory', word2: 'imagination', level: AbstractionLevel.abstract, twoPointAnswers: ['higher cognitive faculties of the human mind', 'mental capacities enabling inner representation beyond immediate perception', 'psychological processes by which humans transcend the present moment', 'faculties that construct subjective experience beyond what is directly given to the senses'], onePointAnswers: ['things the mind does', 'mental abilities', 'things studied in psychology', 'things that involve forming mental pictures', 'things that can be vivid or faint'], thetaValue: 1.5),
      SimilarityItem(word1: 'chance', word2: 'necessity', level: AbstractionLevel.abstract, twoPointAnswers: ['opposing philosophical categories governing the nature of causation', 'abstract principles through which thinkers distinguish what is contingent from what is inevitable', 'fundamental concepts in metaphysics and the philosophy of science describing why things happen', 'complementary poles in the conceptual framework through which human beings make sense of fate and determinism'], onePointAnswers: ['things that affect what happens', 'concepts philosophers write about', 'ideas relevant to science and luck', 'factors that shape outcomes', 'things discussed in debates about free will'], thetaValue: 1.5),
      SimilarityItem(word1: 'time', word2: 'space', level: AbstractionLevel.abstract, twoPointAnswers: ['fundamental dimensions of physical reality', 'abstract continua within which all events and objects are situated', 'basic categories through which existence itself is structured', 'concepts at the heart of physics and metaphysics'], onePointAnswers: ['things that can be measured', 'concepts studied in science', 'things that seem infinite', 'things Einstein wrote about', 'they both can feel limited or vast'], thetaValue: 1.5),
      SimilarityItem(word1: 'law', word2: 'morality', level: AbstractionLevel.abstract, twoPointAnswers: ['systems of norms that regulate human conduct by distinguishing the permissible from the impermissible', 'abstract frameworks governing how people ought to behave, grounded in different forms of authority', 'normative codes defining obligations and prohibitions in personal and social life', 'overlapping but distinct principles by which human action is judged right or wrong'], onePointAnswers: ['rules about right and wrong', 'things that can conflict with each other', 'things studied in philosophy and law', 'guides for how to behave', 'things enforced by society or conscience'], thetaValue: 1.5),
      SimilarityItem(word1: 'truth', word2: 'beauty', level: AbstractionLevel.abstract, twoPointAnswers: ['transcendent ideals pursued across philosophy, art, and science', 'abstract values that cultures universally seek and recognise, though they resist precise definition', 'classical epistemic and aesthetic ideals at the heart of Western philosophical inquiry', 'standards of value that transcend the merely useful or pleasurable'], onePointAnswers: ['things people admire', 'ideals often mentioned together', 'things art tries to capture', 'things that can be subjective', 'concepts studied in philosophy'], thetaValue: 1.5),
    ],
  ];
}
