/// Banque de paires du sous-test Similitudes — de (GÉNÉRÉ par IA, vérifié). 4 niveaux d'abstraction. NE PAS éditer à la main.
library;

import 'similarities_generator.dart';

List<List<SimilarityItem>> buildGermanSimilarityBanks() {
  return [
    // concrete (12 paires)
    [
      SimilarityItem(word1: 'Orange', word2: 'Banane', level: AbstractionLevel.concrete, twoPointAnswers: ['Beides sind Früchte', 'Beides ist Obst', 'Sie gehören zur Gruppe des Obstes', 'Beides sind Nahrungsmittel, die man als Obst bezeichnet'], onePointAnswers: ['Beides wächst an Pflanzen', 'Beides hat eine Schale', 'Man kann beides essen', 'Beides hat Vitamine', 'Beides kauft man im Supermarkt'], thetaValue: -1.5),
      SimilarityItem(word1: 'Hund', word2: 'Katze', level: AbstractionLevel.concrete, twoPointAnswers: ['Beides sind Tiere', 'Beides sind Haustiere', 'Beides sind Säugetiere, die als Haustiere gehalten werden', 'Beides sind domestizierte Tiere'], onePointAnswers: ['Beides hat vier Beine', 'Beides hat Fell', 'Beides macht Geräusche', 'Man muss beides füttern', 'Beides lebt bei Menschen'], thetaValue: -1.5),
      SimilarityItem(word1: 'Hammer', word2: 'Säge', level: AbstractionLevel.concrete, twoPointAnswers: ['Beides sind Werkzeuge', 'Beides ist Handwerkszeug', 'Beides sind Werkzeuge für handwerkliche Arbeiten', 'Beides gehört zum Werkzeug eines Handwerkers'], onePointAnswers: ['Beides hält man in der Hand', 'Beides wird auf dem Bau verwendet', 'Beides kann gefährlich sein', 'Man kauft beides im Baumarkt', 'Beides ist aus Metall'], thetaValue: -1.5),
      SimilarityItem(word1: 'Rose', word2: 'Tulpe', level: AbstractionLevel.concrete, twoPointAnswers: ['Beides sind Blumen', 'Beides sind Blütenpflanzen', 'Beides sind Zierpflanzen bzw. Schnittblumen', 'Beides gehört zur Gruppe der Blumen'], onePointAnswers: ['Beides hat Blütenblätter', 'Beides wächst im Garten', 'Beides hat einen Stiel', 'Beides kauft man beim Blumenhändler', 'Beides ist bunt'], thetaValue: -1.5),
      SimilarityItem(word1: 'Messer', word2: 'Gabel', level: AbstractionLevel.concrete, twoPointAnswers: ['Beides ist Besteck', 'Beides sind Essgeräte', 'Beides ist Tischbesteck', 'Beides gehört zum Besteck beim Essen'], onePointAnswers: ['Beides ist aus Metall', 'Beides verwendet man beim Essen', 'Beides liegt auf dem Tisch', 'Beides wird gespült', 'Beides hält man in der Hand beim Essen'], thetaValue: -1.5),
      SimilarityItem(word1: 'Bus', word2: 'Straßenbahn', level: AbstractionLevel.concrete, twoPointAnswers: ['Beides sind öffentliche Verkehrsmittel', 'Beides sind Transportmittel für Personen', 'Beides fährt im öffentlichen Nahverkehr', 'Beides sind Fahrzeuge des ÖPNV'], onePointAnswers: ['Beides fährt in der Stadt', 'Beides hat viele Sitze', 'Für beides braucht man eine Fahrkarte', 'Beides hält an Haltestellen', 'Beides transportiert viele Menschen'], thetaValue: -1.5),
      SimilarityItem(word1: 'Hemd', word2: 'Hose', level: AbstractionLevel.concrete, twoPointAnswers: ['Beides sind Kleidungsstücke', 'Beides ist Bekleidung', 'Beides sind Kleidungsstücke, die man am Körper trägt', 'Beides gehört zur Kleidung'], onePointAnswers: ['Beides ist aus Stoff', 'Beides kauft man in einem Geschäft', 'Beides muss gewaschen werden', 'Beides gibt es in verschiedenen Größen', 'Beides zieht man morgens an'], thetaValue: -1.5),
      SimilarityItem(word1: 'Tisch', word2: 'Stuhl', level: AbstractionLevel.concrete, twoPointAnswers: ['Beides sind Möbelstücke', 'Beides ist Möbel', 'Beides gehört zur Einrichtung', 'Beides sind Einrichtungsgegenstände'], onePointAnswers: ['Beides steht im Zimmer', 'Beides ist aus Holz', 'Beides kauft man beim Möbelhändler', 'Beides hat Beine', 'Beides gehört zusammen'], thetaValue: -1.5),
      SimilarityItem(word1: 'Geige', word2: 'Gitarre', level: AbstractionLevel.concrete, twoPointAnswers: ['Beides sind Musikinstrumente', 'Beides sind Saiteninstrumente', 'Beides sind Instrumente, auf denen man Musik macht', 'Beides gehört zu den Saiteninstrumenten'], onePointAnswers: ['Beides hat Saiten', 'Beides spielt man mit den Händen', 'Beides ist aus Holz', 'Beides lernt man in der Musikschule', 'Beides wird in Konzerten gespielt'], thetaValue: -1.5),
      SimilarityItem(word1: 'Tasse', word2: 'Glas', level: AbstractionLevel.concrete, twoPointAnswers: ['Beides sind Trinkgefäße', 'Beides sind Gefäße zum Trinken', 'Beides gehört zum Geschirr', 'Beides sind Behälter für Getränke'], onePointAnswers: ['Man trinkt aus beiden', 'Beides hält man in der Hand', 'Beides kommt in die Spülmaschine', 'Beides kann zerbrechen', 'Man füllt beide mit Flüssigkeit'], thetaValue: -1.5),
      SimilarityItem(word1: 'Möhre', word2: 'Kartoffel', level: AbstractionLevel.concrete, twoPointAnswers: ['Beides sind Gemüsesorten', 'Beides ist Gemüse', 'Beides sind Nahrungsmittel pflanzlicher Herkunft, die man als Gemüse bezeichnet', 'Beides gehört zur Gruppe des Gemüses'], onePointAnswers: ['Beides wächst im Boden', 'Beides kann man kochen', 'Beides kauft man im Supermarkt', 'Beides ist eine Beilage beim Essen', 'Beides schält man vor dem Kochen'], thetaValue: -1.5),
      SimilarityItem(word1: 'Amsel', word2: 'Spatz', level: AbstractionLevel.concrete, twoPointAnswers: ['Beides sind Vögel', 'Beides sind Singvögel', 'Beides sind Tiere, die fliegen können', 'Beides sind heimische Wildvögel'], onePointAnswers: ['Beides hat Federn', 'Beides baut Nester', 'Beides macht Geräusche', 'Beides fliegt', 'Beides sieht man im Garten'], thetaValue: -1.5),
    ],
    // functional (15 paires)
    [
      SimilarityItem(word1: 'Hammer', word2: 'Schraubenzieher', level: AbstractionLevel.functional, twoPointAnswers: ['Werkzeuge', 'Handwerkzeuge', 'Geräte für Montage- und Reparaturarbeiten'], onePointAnswers: ['werden mit der Hand gehalten', 'haben einen Griff', 'werden beim Heimwerken benutzt'], thetaValue: -0.5),
      SimilarityItem(word1: 'Boot', word2: 'Flugzeug', level: AbstractionLevel.functional, twoPointAnswers: ['Verkehrsmittel', 'Transportmittel', 'Beförderungsmittel für Personen oder Waren'], onePointAnswers: ['haben einen Motor', 'befördern Passagiere', 'brauchen einen Fahrschein'], thetaValue: -0.5),
      SimilarityItem(word1: 'Kugelschreiber', word2: 'Bleistift', level: AbstractionLevel.functional, twoPointAnswers: ['Schreibgeräte', 'Schreibwerkzeuge', 'Hilfsmittel zum Festhalten von Texten oder Zeichnungen'], onePointAnswers: ['werden mit den Fingern gehalten', 'hinterlassen Spuren auf Papier', 'werden in der Schule benutzt'], thetaValue: -0.5),
      SimilarityItem(word1: 'Messer', word2: 'Schere', level: AbstractionLevel.functional, twoPointAnswers: ['Schneidwerkzeuge', 'Schneidegeräte', 'Geräte zum Durchtrennen von Materialien'], onePointAnswers: ['sind aus Metall', 'sind scharf', 'können gefährlich sein'], thetaValue: -0.5),
      SimilarityItem(word1: 'Stuhl', word2: 'Sitzbank', level: AbstractionLevel.functional, twoPointAnswers: ['Sitzmöbel', 'Sitzgelegenheiten', 'Möbelstücke, auf denen man Platz nehmen kann'], onePointAnswers: ['haben Beine', 'tragen das Gewicht einer Person', 'gibt es drinnen und draußen'], thetaValue: -0.5),
      SimilarityItem(word1: 'Uhr', word2: 'Kalender', level: AbstractionLevel.functional, twoPointAnswers: ['Hilfsmittel zur zeitlichen Orientierung', 'Mittel zur Erfassung und Einteilung der Zeit', 'Instrumente zum Ablesen von Zeit oder Datum'], onePointAnswers: ['haben Zahlen', 'werden täglich benutzt', 'helfen beim Planen des Alltags'], thetaValue: -0.5),
      SimilarityItem(word1: 'Brille', word2: 'Lupe', level: AbstractionLevel.functional, twoPointAnswers: ['Sehhilfen', 'optische Hilfsmittel zur Verbesserung der Sehschärfe', 'Geräte mit Linsen zum besseren Sehen'], onePointAnswers: ['haben Gläser', 'helfen beim Lesen', 'vergrößern oder korrigieren das Bild'], thetaValue: -0.5),
      SimilarityItem(word1: 'Herd', word2: 'Mikrowelle', level: AbstractionLevel.functional, twoPointAnswers: ['Küchengeräte zum Zubereiten von Speisen', 'Geräte zum Erhitzen oder Garen von Lebensmitteln', 'Geräte, mit denen man Essen kocht oder erwärmt'], onePointAnswers: ['stehen in der Küche', 'werden heiß', 'haben Bedienknöpfe'], thetaValue: -0.5),
      SimilarityItem(word1: 'Bügeleisen', word2: 'Wäschetrockner', level: AbstractionLevel.functional, twoPointAnswers: ['Geräte zur Wäschepflege', 'Haushaltselektrogeräte für die Nachbehandlung von Wäsche', 'Hilfsmittel, um Kleidung nach dem Waschen in Ordnung zu bringen'], onePointAnswers: ['brauchen Strom', 'erzeugen Wärme', 'kommen nach dem Waschen zum Einsatz'], thetaValue: -0.5),
      SimilarityItem(word1: 'Thermometer', word2: 'Blutdruckmessgerät', level: AbstractionLevel.functional, twoPointAnswers: ['medizinische Messgeräte', 'Geräte zur Messung von Körperwerten', 'diagnostische Hilfsmittel zur Überwachung der Gesundheit'], onePointAnswers: ['benutzt der Arzt', 'haben eine Messskala', 'zeigen Zahlen an'], thetaValue: -0.5),
      SimilarityItem(word1: 'Aufzug', word2: 'Treppe', level: AbstractionLevel.functional, twoPointAnswers: ['Zugangsmittel zwischen verschiedenen Stockwerken', 'Einrichtungen zur vertikalen Fortbewegung in Gebäuden', 'Wege, um in einem Gebäude von einer Etage in eine andere zu gelangen'], onePointAnswers: ['sind in Gebäuden', 'verbinden Stockwerke', 'gibt es in Einkaufszentren und Wohnhäusern'], thetaValue: -0.5),
      SimilarityItem(word1: 'Zeitung', word2: 'Radio', level: AbstractionLevel.functional, twoPointAnswers: ['Informationsmedien', 'Medien zur Verbreitung von Nachrichten', 'Mittel, über die man sich über aktuelle Ereignisse informiert'], onePointAnswers: ['berichten über Neuigkeiten', 'gibt es täglich', 'werden von vielen Menschen genutzt'], thetaValue: -0.5),
      SimilarityItem(word1: 'Waage', word2: 'Maßband', level: AbstractionLevel.functional, twoPointAnswers: ['Messinstrumente', 'Geräte zum Messen von Gewicht oder Länge', 'Hilfsmittel zur genauen Bestimmung von Maßen'], onePointAnswers: ['zeigen Zahlen an', 'werden im Alltag genutzt', 'helfen beim Abmessen oder Einteilen'], thetaValue: -0.5),
      SimilarityItem(word1: 'Schlüssel', word2: 'Zugangscode', level: AbstractionLevel.functional, twoPointAnswers: ['Zugangsmittel', 'Mittel zur Authentifizierung und zum Öffnen gesicherter Bereiche', 'Hilfsmittel, um Zugang zu einem gesperrten Bereich zu erhalten'], onePointAnswers: ['werden gebraucht, um etwas zu öffnen', 'schützen vor unbefugtem Zutritt', 'muss man sich merken oder bei sich tragen'], thetaValue: -0.5),
      SimilarityItem(word1: 'Landkarte', word2: 'Kompass', level: AbstractionLevel.functional, twoPointAnswers: ['Navigationshilfsmittel', 'Orientierungsmittel zur Bestimmung des Weges', 'Hilfsmittel zur räumlichen Orientierung'], onePointAnswers: ['benutzt man auf Reisen oder beim Wandern', 'helfen, sich nicht zu verirren', 'zeigen Richtungen oder Orte an'], thetaValue: -0.5),
    ],
    // categorical (13 paires)
    [
      SimilarityItem(word1: 'Geige', word2: 'Flöte', level: AbstractionLevel.categorical, twoPointAnswers: ['Musikinstrumente', 'Instrumente zum Musizieren', 'Mittel zur Klangerzeugung in der Musik'], onePointAnswers: ['Man spielt beide in einem Orchester', 'Beide erzeugen Töne', 'Beide erfordern jahrelange Übung'], thetaValue: 0.5),
      SimilarityItem(word1: 'Angst', word2: 'Trauer', level: AbstractionLevel.categorical, twoPointAnswers: ['Gefühle', 'Emotionen', 'Gemütszustände'], onePointAnswers: ['Beide können Menschen belasten', 'Beide spürt man körperlich', 'Beide entstehen als Reaktion auf Erlebnisse'], thetaValue: 0.5),
      SimilarityItem(word1: 'Eiche', word2: 'Tanne', level: AbstractionLevel.categorical, twoPointAnswers: ['Waldbäume', 'Bäume', 'Holzgewächse'], onePointAnswers: ['Beide wachsen im deutschen Wald', 'Beide können sehr alt werden', 'Beide liefern Bauholz'], thetaValue: 0.5),
      SimilarityItem(word1: 'Schach', word2: 'Skat', level: AbstractionLevel.categorical, twoPointAnswers: ['Gesellschaftsspiele', 'Strategiespiele', 'Spiele, die Denkfähigkeit erfordern'], onePointAnswers: ['Beide spielen mehrere Personen zusammen', 'Beide brauchen Konzentration', 'Man gewinnt oder verliert dabei'], thetaValue: 0.5),
      SimilarityItem(word1: 'U-Bahn', word2: 'Straßenbahn', level: AbstractionLevel.categorical, twoPointAnswers: ['Schienenfahrzeuge des öffentlichen Nahverkehrs', 'Öffentliche Verkehrsmittel', 'Schienengebundene Transportmittel'], onePointAnswers: ['Beide fahren auf festen Strecken', 'Beide befördern viele Fahrgäste', 'Beide fährt man mit einem Fahrschein'], thetaValue: 0.5),
      SimilarityItem(word1: 'Regen', word2: 'Schnee', level: AbstractionLevel.categorical, twoPointAnswers: ['Niederschlagsformen', 'Wettererscheinungen', 'Atmosphärische Niederschläge'], onePointAnswers: ['Beide fallen vom Himmel', 'Beide bestehen aus Wasser', 'Beide machen die Straße nass bzw. glatt'], thetaValue: 0.5),
      SimilarityItem(word1: 'Kuchen', word2: 'Eis', level: AbstractionLevel.categorical, twoPointAnswers: ['Süßspeisen', 'Desserts', 'Naschwerk'], onePointAnswers: ['Beide schmecken süß', 'Beide isst man zum Vergnügen', 'Beide gelten als Belohnung oder Genuss'], thetaValue: 0.5),
      SimilarityItem(word1: 'Richter', word2: 'Staatsanwalt', level: AbstractionLevel.categorical, twoPointAnswers: ['Juristen', 'Rechtsberufe', 'Berufe in der Justiz'], onePointAnswers: ['Beide arbeiten im Gericht', 'Beide haben Jura studiert', 'Beide sind am Strafverfahren beteiligt'], thetaValue: 0.5),
      SimilarityItem(word1: 'Fahrrad', word2: 'Motorrad', level: AbstractionLevel.categorical, twoPointAnswers: ['Zweiräder', 'Fortbewegungsmittel', 'Fahrzeuge mit zwei Rädern'], onePointAnswers: ['Beide haben zwei Räder', 'Beide fährt man auf der Straße', 'Beide brauchen einen Lenker'], thetaValue: 0.5),
      SimilarityItem(word1: 'Neid', word2: 'Scham', level: AbstractionLevel.categorical, twoPointAnswers: ['Soziale Gefühle', 'Selbstbezogene Emotionen', 'Gefühle'], onePointAnswers: ['Beide entstehen im Umgang mit anderen', 'Beide können innerlich belasten', 'Beide kennt fast jeder Mensch'], thetaValue: 0.5),
      SimilarityItem(word1: 'Mikrowelle', word2: 'Toaster', level: AbstractionLevel.categorical, twoPointAnswers: ['Elektrische Küchengeräte', 'Haushaltsgeräte zur Speisenzubereitung', 'Küchengeräte'], onePointAnswers: ['Beide erwärmen Lebensmittel', 'Beide stehen in der Küche', 'Beide brauchen Strom'], thetaValue: 0.5),
      SimilarityItem(word1: 'Roman', word2: 'Kurzgeschichte', level: AbstractionLevel.categorical, twoPointAnswers: ['Literarische Prosaformen', 'Erzählliteraturgattungen', 'Formen der erzählenden Literatur'], onePointAnswers: ['Beide sind schriftliche Texte', 'Beide erzählen eine Geschichte', 'Beide liest man in einem Buch oder Heft'], thetaValue: 0.5),
      SimilarityItem(word1: 'Apotheker', word2: 'Pflegefachkraft', level: AbstractionLevel.categorical, twoPointAnswers: ['Heilberufe', 'Berufe im Gesundheitswesen', 'Medizinische Fachkräfte'], onePointAnswers: ['Beide helfen kranken Menschen', 'Beide haben eine medizinische Ausbildung', 'Beide tragen Verantwortung für das Wohlbefinden von Patienten'], thetaValue: 0.5),
    ],
    // abstract (12 paires)
    [
      SimilarityItem(word1: 'Freiheit', word2: 'Gerechtigkeit', level: AbstractionLevel.abstract, twoPointAnswers: ['Beides sind abstrakte normative Grundwerte einer Gemeinschaft', 'Ethische Leitprinzipien, die das gesellschaftliche Zusammenleben ordnen', 'Ideale, nach denen Gesellschaften ihre Institutionen ausrichten'], onePointAnswers: ['Beide sind für den Menschen erstrebenswert', 'Beide kommen im Grundgesetz vor', 'Man kämpft für beide', 'Beide betreffen das Verhältnis zwischen Individuum und Gemeinschaft'], thetaValue: 1.5),
      SimilarityItem(word1: 'Mut', word2: 'Ausdauer', level: AbstractionLevel.abstract, twoPointAnswers: ['Beides sind Charaktertugenden, die zielbewusstes Handeln ermöglichen', 'Moralische Dispositionen, die innere Hürden überwinden', 'Tugenden, die das Handeln trotz Widerstand aufrechterhalten'], onePointAnswers: ['Beide sind positive Charaktereigenschaften', 'Beide helfen, schwierige Situationen zu meistern', 'Beide setzt man für etwas ein, das einem wichtig ist', 'Beide gelten als Zeichen von Stärke'], thetaValue: 1.5),
      SimilarityItem(word1: 'Vertrauen', word2: 'Hoffnung', level: AbstractionLevel.abstract, twoPointAnswers: ['Beides sind innere Grundhaltungen gegenüber einer ungewissen Zukunft', 'Kognitive Einstellungen, die Unsicherheit überbrücken und Handeln ermöglichen', 'Psychische Zustände, die trotz fehlender Gewissheit Orientierung geben'], onePointAnswers: ['Beide sind positive innere Zustände', 'Beide geben Kraft in schwierigen Zeiten', 'Beide können enttäuscht werden', 'Beide richten sich auf etwas, das noch nicht gesichert ist'], thetaValue: 1.5),
      SimilarityItem(word1: 'Gesetz', word2: 'Moral', level: AbstractionLevel.abstract, twoPointAnswers: ['Beides sind normative Ordnungssysteme, die menschliches Verhalten regulieren', 'Regelwerke, die in einer Gesellschaft zwischen richtig und falsch unterscheiden', 'Systeme von Normen, die Handlungen bewerten und lenken'], onePointAnswers: ['Beide unterscheiden erlaubtes von verbotenem Verhalten', 'Beide schützen Menschen voreinander', 'Beide kann man verletzen oder brechen', 'Beide gibt es in jeder menschlichen Gesellschaft'], thetaValue: 1.5),
      SimilarityItem(word1: 'Sprache', word2: 'Mathematik', level: AbstractionLevel.abstract, twoPointAnswers: ['Beides sind formale Zeichensysteme zur Darstellung und Strukturierung von Wirklichkeit', 'Abstrakte Regelsysteme, die Bedeutung durch definierte Symbole und Syntax erzeugen', 'Universelle Ausdruckssysteme, die Denkinhalte präzise übertragbar machen'], onePointAnswers: ['Beide haben feste Regeln und eine eigene Grammatik', 'Beide sind Werkzeuge des Denkens und der Erkenntnis', 'Beide lernt man systematisch', 'Beide ermöglichen Kommunikation und Verständigung'], thetaValue: 1.5),
      SimilarityItem(word1: 'Traum', word2: 'Erinnerung', level: AbstractionLevel.abstract, twoPointAnswers: ['Beides sind subjektive mentale Konstrukte, die Erfahrungen jenseits der unmittelbaren Gegenwart abbilden', 'Innere psychische Prozesse, bei denen der Geist Erlebnisse verarbeitet und neu zusammensetzt', 'Bewusstseinszustände, in denen vergangene oder imaginierte Inhalte erlebt werden'], onePointAnswers: ['Beides findet im Kopf statt', 'Beide können lebhaft und bildreich sein', 'Beide können sich mit der Zeit verändern oder verblassen', 'Beide sind nicht immer zuverlässig oder wahrheitsgetreu'], thetaValue: 1.5),
      SimilarityItem(word1: 'Krieg', word2: 'Epidemie', level: AbstractionLevel.abstract, twoPointAnswers: ['Beides sind kollektive Ausnahmezustände, die ganze Gesellschaften erschüttern', 'Massenphänomene, die staatliche und soziale Strukturen unter extremen Druck setzen', 'Gesellschaftliche Krisen, die das Leben ganzer Gemeinschaften fundamental verändern'], onePointAnswers: ['Beide fordern viele Menschenleben', 'Beide sind große Katastrophen', 'Beide verändern den Lauf der Geschichte', 'Beide erfordern außerordentliche Maßnahmen des Staates'], thetaValue: 1.5),
      SimilarityItem(word1: 'Schönheit', word2: 'Wahrheit', level: AbstractionLevel.abstract, twoPointAnswers: ['Beides sind philosophische Wertbegriffe, nach denen Menschen streben', 'Transzendente Ideale, die als objektive Maßstäbe menschlichen Urteilens gelten', 'Abstrakte Kategorien, durch die Menschen die Welt bewerten und deuten'], onePointAnswers: ['Beide sind schwer eindeutig zu definieren', 'Beide sind erstrebenswert', 'Beide spielen in der Kunst eine zentrale Rolle', 'Beide können subjektiv wahrgenommen werden'], thetaValue: 1.5),
      SimilarityItem(word1: 'Zeit', word2: 'Raum', level: AbstractionLevel.abstract, twoPointAnswers: ['Beides sind grundlegende Dimensionen, in denen menschliche Erfahrung stattfindet', 'Fundamentale Anschauungsformen, die jede Wahrnehmung von Wirklichkeit strukturieren', 'Apriorische Kategorien, ohne die Erleben und Erkenntnis nicht möglich sind'], onePointAnswers: ['Beide sind messbar und haben Einheiten', 'Beide sind unbegrenzt und ohne Ende', 'Beide sind Grundbegriffe der Physik', 'Beide kann man nicht berühren oder festhalten'], thetaValue: 1.5),
      SimilarityItem(word1: 'Kunst', word2: 'Wissenschaft', level: AbstractionLevel.abstract, twoPointAnswers: ['Beides sind systematische Formen menschlichen Erkennens und Deutens der Wirklichkeit', 'Kulturelle Tätigkeiten, durch die Menschen die Welt verstehen und gestalten', 'Menschliche Ausdrucks- und Erkenntnisweisen, die nach tieferen Einsichten suchen'], onePointAnswers: ['Beide erfordern Kreativität und intensive Auseinandersetzung', 'Beide hinterlassen Werke, die über den Schöpfer hinaus Bestand haben', 'Beide brauchen Ausbildung und systematisches Üben', 'Beide treiben die menschliche Zivilisation voran'], thetaValue: 1.5),
      SimilarityItem(word1: 'Macht', word2: 'Wissen', level: AbstractionLevel.abstract, twoPointAnswers: ['Beides sind immaterielle Ressourcen, die gesellschaftlichen Einfluss verleihen', 'Mittel, durch die Menschen Kontrolle über ihre soziale und materielle Umwelt gewinnen', 'Formen von Kapital, die Handlungsspielräume erweitern und andere beeinflussen'], onePointAnswers: ['Beide sind wertvoll und begehrt', 'Beide können angesammelt und weitergegeben werden', 'Beide können missbraucht werden', 'Beide verleihen demjenigen Vorteile, der sie besitzt'], thetaValue: 1.5),
      SimilarityItem(word1: 'Schicksal', word2: 'Zufall', level: AbstractionLevel.abstract, twoPointAnswers: ['Beides sind abstrakte Konzepte zur Deutung von Ereignissen, die dem menschlichen Willen entzogen scheinen', 'Metaphysische Kategorien, mit denen Menschen die Kontingenz ihres Lebens erklären', 'Begriffe, durch die das Unverfügbare und Unvorhersehbare im menschlichen Leben gedeutet wird'], onePointAnswers: ['Beide beschreiben Ereignisse, die man nicht selbst herbeigeführt hat', 'Beide spielen in Philosophie und Religion eine wichtige Rolle', 'Beide betreffen Dinge, die außerhalb der eigenen Kontrolle liegen', 'Beide können den Lauf eines Lebens entscheidend verändern'], thetaValue: 1.5),
    ],
  ];
}
