/// Banque de paires du sous-test Similitudes — pt (GÉNÉRÉ par IA, vérifié). 4 niveaux d'abstraction. NE PAS éditer à la main.
library;

import 'similarities_generator.dart';

List<List<SimilarityItem>> buildPortugueseSimilarityBanks() {
  return [
    // concrete (12 paires)
    [
      SimilarityItem(word1: 'laranja', word2: 'banana', level: AbstractionLevel.concrete, twoPointAnswers: ['São frutas', 'Ambas são frutas', 'São um tipo de fruta', 'Pertencem ao grupo das frutas'], onePointAnswers: ['São alimentos', 'Têm casca', 'Comem-se como sobremesa', 'Crescem em plantas', 'São coloridas'], thetaValue: -1.5),
      SimilarityItem(word1: 'cão', word2: 'gato', level: AbstractionLevel.concrete, twoPointAnswers: ['São animais domésticos', 'Ambos são animais de companhia', 'São animais de estimação', 'Pertencem ao grupo dos animais de estimação'], onePointAnswers: ['São animais', 'Têm pelos', 'Vivem em casa', 'Fazem companhia às pessoas', 'Comem-se ração'], thetaValue: -1.5),
      SimilarityItem(word1: 'cadeira', word2: 'sofá', level: AbstractionLevel.concrete, twoPointAnswers: ['São móveis para sentar', 'Ambos são assentos', 'São peças de mobiliário para sentar', 'Servem para as pessoas se sentarem'], onePointAnswers: ['Estão em casa', 'São feitos de madeira ou tecido', 'Fazem parte do mobiliário', 'Servem para descansar', 'Encontram-se na sala'], thetaValue: -1.5),
      SimilarityItem(word1: 'rosa', word2: 'cravo', level: AbstractionLevel.concrete, twoPointAnswers: ['São flores', 'Ambos são tipos de flores', 'São flores de jardim', 'Pertencem ao grupo das flores'], onePointAnswers: ['São plantas', 'Têm pétalas', 'Cheiram bem', 'Usam-se em buquês', 'Crescem em jardins'], thetaValue: -1.5),
      SimilarityItem(word1: 'martelo', word2: 'chave de fendas', level: AbstractionLevel.concrete, twoPointAnswers: ['São ferramentas', 'Ambos são instrumentos de trabalho manual', 'São ferramentas manuais', 'Pertencem ao grupo das ferramentas'], onePointAnswers: ['Servem para arranjar coisas', 'São de metal', 'Usam-se em bricolage', 'Têm cabo', 'Compram-se numa loja de ferragens'], thetaValue: -1.5),
      SimilarityItem(word1: 'camisa', word2: 'calças', level: AbstractionLevel.concrete, twoPointAnswers: ['São peças de roupa', 'Ambos são artigos de vestuário', 'São roupas que se vestem', 'Pertencem ao grupo do vestuário'], onePointAnswers: ['São de tecido', 'Usam-se todos os dias', 'Compram-se numa loja de roupa', 'Podem ser de algodão', 'Podem ser lavadas na máquina'], thetaValue: -1.5),
      SimilarityItem(word1: 'carro', word2: 'autocarro', level: AbstractionLevel.concrete, twoPointAnswers: ['São meios de transporte', 'Ambos são veículos', 'São transportes rodoviários', 'Pertencem ao grupo dos veículos motorizados'], onePointAnswers: ['Têm rodas', 'Usam combustível ou eletricidade', 'Andam na estrada', 'Têm motor', 'Têm portas'], thetaValue: -1.5),
      SimilarityItem(word1: 'piano', word2: 'guitarra', level: AbstractionLevel.concrete, twoPointAnswers: ['São instrumentos musicais', 'Ambos são instrumentos de música', 'São instrumentos com que se faz música', 'Pertencem ao grupo dos instrumentos musicais'], onePointAnswers: ['Fazem barulho', 'Usam-se em concertos', 'Tocam-se com as mãos', 'São usados por músicos', 'Podem acompanhar canções'], thetaValue: -1.5),
      SimilarityItem(word1: 'prato', word2: 'taça', level: AbstractionLevel.concrete, twoPointAnswers: ['São louça', 'Ambos são utensílios de mesa', 'São recipientes para servir alimentos', 'Pertencem ao grupo dos utensílios de mesa'], onePointAnswers: ['São de cerâmica ou vidro', 'Usam-se para comer', 'Lavam-se na máquina da louça', 'Estão na cozinha', 'Empilham-se no armário'], thetaValue: -1.5),
      SimilarityItem(word1: 'leão', word2: 'tigre', level: AbstractionLevel.concrete, twoPointAnswers: ['São felinos', 'Ambos são grandes felinos', 'São animais da mesma família dos gatos', 'Pertencem ao grupo dos felinos'], onePointAnswers: ['São animais perigosos', 'Vivem na selva ou savana', 'São predadores', 'Têm garras', 'São animais selvagens'], thetaValue: -1.5),
      SimilarityItem(word1: 'pão', word2: 'bolo', level: AbstractionLevel.concrete, twoPointAnswers: ['São produtos de padaria', 'Ambos são alimentos feitos com farinha', 'São produtos de forno', 'Pertencem ao grupo dos produtos de padaria e pastelaria'], onePointAnswers: ['São alimentos', 'Fazem-se com farinha', 'Compram-se na padaria', 'Comem-se ao pequeno-almoço', 'Têm crosta'], thetaValue: -1.5),
      SimilarityItem(word1: 'mesa', word2: 'estante', level: AbstractionLevel.concrete, twoPointAnswers: ['São móveis', 'Ambos são peças de mobiliário', 'São móveis de casa', 'Pertencem ao grupo do mobiliário doméstico'], onePointAnswers: ['São feitos de madeira', 'Estão em casa', 'Têm prateleiras ou superfícies', 'Compram-se numa loja de móveis', 'Servem para guardar ou apoiar objetos'], thetaValue: -1.5),
    ],
    // functional (16 paires)
    [
      SimilarityItem(word1: 'martelo', word2: 'chave de parafusos', level: AbstractionLevel.functional, twoPointAnswers: ['servem para fixar e montar coisas', 'usam-se para fazer reparações e construções'], onePointAnswers: ['têm cabo', 'são feitas de metal', 'encontram-se numa caixa de ferramentas', 'usam-se em trabalhos manuais'], thetaValue: -0.5),
      SimilarityItem(word1: 'barco', word2: 'avião', level: AbstractionLevel.functional, twoPointAnswers: ['servem para transportar pessoas ou mercadorias de um lugar para outro', 'são meios de transporte usados em viagens'], onePointAnswers: ['têm motor', 'fazem viagens longas', 'transportam passageiros', 'são conduzidos por um piloto ou capitão'], thetaValue: -0.5),
      SimilarityItem(word1: 'faca', word2: 'tesoura', level: AbstractionLevel.functional, twoPointAnswers: ['servem para cortar', 'são utilizadas para separar ou dividir materiais'], onePointAnswers: ['têm lâmina afiada', 'são feitas de metal', 'podem ser perigosas se mal utilizadas', 'têm cabo ou pega'], thetaValue: -0.5),
      SimilarityItem(word1: 'relógio', word2: 'calendário', level: AbstractionLevel.functional, twoPointAnswers: ['servem para nos orientar no tempo', 'ajudam a saber quando ocorrem os acontecimentos'], onePointAnswers: ['têm números', 'são usados no quotidiano', 'estão presentes em quase todas as casas', 'ajudam a organizar a vida'], thetaValue: -0.5),
      SimilarityItem(word1: 'vassoura', word2: 'aspirador', level: AbstractionLevel.functional, twoPointAnswers: ['servem para limpar o chão retirando o pó e a sujidade', 'são usados para manter os espaços limpos'], onePointAnswers: ['usam-se dentro de casa', 'têm uma cabeça que contacta com o chão', 'precisam de ser esvaziados ou limpos', 'são utensílios de limpeza doméstica'], thetaValue: -0.5),
      SimilarityItem(word1: 'lápis', word2: 'caneta', level: AbstractionLevel.functional, twoPointAnswers: ['servem para escrever ou desenhar', 'são instrumentos utilizados para deixar marcas no papel'], onePointAnswers: ['são usados na escola e no trabalho', 'têm ponta', 'cabem na mão', 'usam-se para tomar notas'], thetaValue: -0.5),
      SimilarityItem(word1: 'fogão', word2: 'micro-ondas', level: AbstractionLevel.functional, twoPointAnswers: ['servem para cozinhar e aquecer alimentos', 'são usados para preparar refeições'], onePointAnswers: ['consomem energia', 'estão na cozinha', 'produzem calor', 'têm controlos de temperatura ou potência'], thetaValue: -0.5),
      SimilarityItem(word1: 'óculos', word2: 'lentes de contacto', level: AbstractionLevel.functional, twoPointAnswers: ['servem para corrigir problemas de visão', 'ajudam as pessoas a ver com nitidez'], onePointAnswers: ['são prescritos por um oftalmologista', 'têm lentes graduadas', 'são usados todos os dias por quem tem problemas de visão', 'existem em diferentes graduações'], thetaValue: -0.5),
      SimilarityItem(word1: 'termómetro', word2: 'balança', level: AbstractionLevel.functional, twoPointAnswers: ['são instrumentos que servem para medir', 'fornecem valores precisos sobre uma propriedade física'], onePointAnswers: ['têm escala numérica', 'são usados em medicina, ciência ou cozinha', 'dão uma leitura objetiva', 'precisam de ser calibrados para ser exactos'], thetaValue: -0.5),
      SimilarityItem(word1: 'telefone', word2: 'carta', level: AbstractionLevel.functional, twoPointAnswers: ['servem para comunicar com outras pessoas à distância', 'permitem transmitir mensagens entre pessoas que não estão no mesmo lugar'], onePointAnswers: ['ligam pessoas separadas geograficamente', 'podem conter palavras ou mensagens pessoais', 'são usados para contactar alguém', 'requerem um destinatário'], thetaValue: -0.5),
      SimilarityItem(word1: 'chapéu de chuva', word2: 'impermeável', level: AbstractionLevel.functional, twoPointAnswers: ['servem para proteger do mau tempo, sobretudo da chuva', 'são usados para não ficar molhado quando chove'], onePointAnswers: ['usam-se principalmente no inverno ou em dias de chuva', 'são feitos de materiais resistentes à água', 'protegem o corpo', 'são artigos de uso exterior'], thetaValue: -0.5),
      SimilarityItem(word1: 'livro', word2: 'jornal', level: AbstractionLevel.functional, twoPointAnswers: ['servem para ler e transmitir informação escrita', 'são publicações usadas para obter conhecimento ou notícias'], onePointAnswers: ['são feitos de papel', 'têm texto escrito', 'são impressos ou editados', 'encontram-se em bibliotecas, bancas ou livrarias'], thetaValue: -0.5),
      SimilarityItem(word1: 'frigorífico', word2: 'arca congeladora', level: AbstractionLevel.functional, twoPointAnswers: ['servem para conservar alimentos durante mais tempo', 'são usados para manter os alimentos em bom estado através do frio'], onePointAnswers: ['funcionam com eletricidade', 'têm porta com vedante', 'estão normalmente na cozinha ou dispensa', 'produzem frio através de um motor'], thetaValue: -0.5),
      SimilarityItem(word1: 'cadeira', word2: 'banco', level: AbstractionLevel.functional, twoPointAnswers: ['servem para se sentar', 'são usados para suportar o peso do corpo numa posição sentada'], onePointAnswers: ['têm pernas', 'são feitos de madeira, metal ou plástico', 'encontram-se em casas, escritórios e espaços públicos', 'são peças de mobiliário'], thetaValue: -0.5),
      SimilarityItem(word1: 'sabão', word2: 'detergente', level: AbstractionLevel.functional, twoPointAnswers: ['servem para limpar e remover sujidade', 'são usados para lavar e higienizar superfícies, roupa ou o corpo'], onePointAnswers: ['fazem espuma em contacto com água', 'têm substâncias que dissolvem a gordura', 'são usados nas lides domésticas', 'existem em versões líquidas ou sólidas'], thetaValue: -0.5),
      SimilarityItem(word1: 'mapa', word2: 'bússola', level: AbstractionLevel.functional, twoPointAnswers: ['servem para ajudar a orientar e a encontrar o caminho', 'são usados para navegação e deslocação no espaço'], onePointAnswers: ['são usados em caminhadas e viagens', 'eram essenciais antes dos telemóveis com GPS', 'ajudam a não se perder', 'requerem saber interpretá-los'], thetaValue: -0.5),
    ],
    // categorical (15 paires)
    [
      SimilarityItem(word1: 'violino', word2: 'piano', level: AbstractionLevel.categorical, twoPointAnswers: ['São instrumentos musicais', 'Ambos são instrumentos musicais', 'Pertencem ao grupo dos instrumentos musicais'], onePointAnswers: ['Fazem música', 'São usados em concertos', 'Produzem sons'], thetaValue: 0.5),
      SimilarityItem(word1: 'raiva', word2: 'alegria', level: AbstractionLevel.categorical, twoPointAnswers: ['São emoções', 'Ambas são sentimentos humanos', 'Pertencem ao grupo das emoções'], onePointAnswers: ['São sentidas pelas pessoas', 'Afetam o comportamento', 'Podem ser expressas no rosto'], thetaValue: 0.5),
      SimilarityItem(word1: 'crocodilo', word2: 'cobra', level: AbstractionLevel.categorical, twoPointAnswers: ['São répteis', 'Ambos são animais répteis', 'Pertencem ao grupo dos répteis'], onePointAnswers: ['São animais', 'Vivem em climas quentes', 'Têm escamas'], thetaValue: 0.5),
      SimilarityItem(word1: 'médico', word2: 'enfermeiro', level: AbstractionLevel.categorical, twoPointAnswers: ['São profissionais de saúde', 'Ambos trabalham na área da saúde', 'São profissões ligadas aos cuidados de saúde'], onePointAnswers: ['Trabalham em hospitais', 'Cuidam de doentes', 'Ajudam pessoas doentes'], thetaValue: 0.5),
      SimilarityItem(word1: 'triângulo', word2: 'quadrado', level: AbstractionLevel.categorical, twoPointAnswers: ['São figuras geométricas', 'Ambos são polígonos', 'São formas geométricas planas com lados retos'], onePointAnswers: ['São formas', 'Têm ângulos', 'São figuras fechadas'], thetaValue: 0.5),
      SimilarityItem(word1: 'romancista', word2: 'poeta', level: AbstractionLevel.categorical, twoPointAnswers: ['São escritores', 'Ambos são criadores literários', 'Pertencem ao grupo dos autores de literatura'], onePointAnswers: ['Escrevem', 'Publicam livros', 'Trabalham com palavras'], thetaValue: 0.5),
      SimilarityItem(word1: 'trigo', word2: 'milho', level: AbstractionLevel.categorical, twoPointAnswers: ['São cereais', 'Ambos são tipos de cereal', 'Pertencem ao grupo dos cereais'], onePointAnswers: ['São plantas', 'São alimentos', 'Crescem em campos'], thetaValue: 0.5),
      SimilarityItem(word1: 'tribunal', word2: 'parlamento', level: AbstractionLevel.categorical, twoPointAnswers: ['São instituições do Estado', 'Ambos são órgãos do poder público', 'São instituições soberanas do Estado de direito'], onePointAnswers: ['São edifícios importantes', 'Têm funcionários públicos', 'São locais onde se tomam decisões'], thetaValue: 0.5),
      SimilarityItem(word1: 'pessimismo', word2: 'otimismo', level: AbstractionLevel.categorical, twoPointAnswers: ['São atitudes perante a vida', 'Ambas são formas de encarar o mundo', 'São perspetivas ou visões sobre a existência'], onePointAnswers: ['Influenciam o comportamento', 'Estão ligados ao humor', 'Afetam as relações com os outros'], thetaValue: 0.5),
      SimilarityItem(word1: 'budismo', word2: 'islamismo', level: AbstractionLevel.categorical, twoPointAnswers: ['São religiões', 'Ambos são sistemas de crença religiosa', 'Pertencem ao grupo das religiões mundiais'], onePointAnswers: ['Têm seguidores', 'Ensinam valores morais', 'Têm rituais e práticas'], thetaValue: 0.5),
      SimilarityItem(word1: 'ansiedade', word2: 'depressão', level: AbstractionLevel.categorical, twoPointAnswers: ['São perturbações mentais', 'Ambas são doenças psicológicas', 'Pertencem ao grupo das perturbações de saúde mental'], onePointAnswers: ['Afetam o bem-estar', 'Podem precisar de tratamento', 'Afetam o dia a dia das pessoas'], thetaValue: 0.5),
      SimilarityItem(word1: 'fotografia', word2: 'pintura', level: AbstractionLevel.categorical, twoPointAnswers: ['São formas de arte visual', 'Ambas são artes plásticas', 'Pertencem ao grupo das artes visuais'], onePointAnswers: ['Criam imagens', 'São formas de expressão', 'Podem ser expostas em museus'], thetaValue: 0.5),
      SimilarityItem(word1: 'democracia', word2: 'monarquia', level: AbstractionLevel.categorical, twoPointAnswers: ['São sistemas de governo', 'Ambas são formas de organização política do Estado', 'Pertencem ao grupo dos regimes políticos'], onePointAnswers: ['Têm leis', 'Organizam a sociedade', 'Implicam um poder governante'], thetaValue: 0.5),
      SimilarityItem(word1: 'telescópio', word2: 'microscópio', level: AbstractionLevel.categorical, twoPointAnswers: ['São instrumentos ópticos', 'Ambos são instrumentos científicos de observação', 'Pertencem ao grupo dos instrumentos de ampliação óptica'], onePointAnswers: ['Usam lentes', 'São usados em ciência', 'Permitem ver melhor'], thetaValue: 0.5),
      SimilarityItem(word1: 'inveja', word2: 'orgulho', level: AbstractionLevel.categorical, twoPointAnswers: ['São emoções morais', 'Ambas são sentimentos ligados à avaliação social de si próprio', 'Pertencem ao grupo das emoções autoconscientes'], onePointAnswers: ['São sentidas pelas pessoas', 'Podem afetar relações', 'Estão ligadas à forma como nos vemos'], thetaValue: 0.5),
    ],
    // abstract (12 paires)
    [
      SimilarityItem(word1: 'liberdade', word2: 'justiça', level: AbstractionLevel.abstract, twoPointAnswers: ['valores abstratos fundamentais', 'ideais que regem a sociedade', 'princípios filosóficos e morais', 'direitos ou valores humanos universais'], onePointAnswers: ['conceitos importantes para as pessoas', 'coisas que toda a gente quer', 'direitos que os cidadãos defendem', 'palavras usadas em política', 'temas filosóficos'], thetaValue: 1.5),
      SimilarityItem(word1: 'elogio', word2: 'castigo', level: AbstractionLevel.abstract, twoPointAnswers: ['formas de influenciar o comportamento', 'mecanismos de regulação social ou educacional', 'instrumentos de reforço ou correção da conduta', 'meios de moldar o comportamento de alguém'], onePointAnswers: ['reações a um comportamento', 'coisas que os pais fazem aos filhos', 'formas de responder a uma ação', 'consequências de um ato', 'ferramentas da educação'], thetaValue: 1.5),
      SimilarityItem(word1: 'esperança', word2: 'fé', level: AbstractionLevel.abstract, twoPointAnswers: ['disposições psicológicas baseadas na crença e não na certeza', 'atitudes de confiança perante a incerteza', 'estados mentais de comprometimento com algo não verificável', 'orientações da mente para além do que é demonstrável'], onePointAnswers: ['sentimentos positivos', 'coisas em que as pessoas acreditam', 'relacionadas com a religião', 'conforto em momentos difíceis', 'estados de espírito'], thetaValue: 1.5),
      SimilarityItem(word1: 'poder', word2: 'riqueza', level: AbstractionLevel.abstract, twoPointAnswers: ['recursos que conferem vantagem e controlo sobre os outros', 'formas de capital que ampliam a capacidade de agir no mundo', 'bens que determinam o estatuto e a influência social', 'meios de exercer domínio sobre pessoas ou situações'], onePointAnswers: ['coisas que as pessoas desejam ter', 'sinais de sucesso', 'vantagens na vida', 'temas ligados à política e à economia', 'fontes de prestígio'], thetaValue: 1.5),
      SimilarityItem(word1: 'silêncio', word2: 'escuridão', level: AbstractionLevel.abstract, twoPointAnswers: ['ausências de estímulo sensorial', 'estados de privação percetiva', 'condições em que um sentido fica sem input', 'ausências que moldam a experiência subjetiva'], onePointAnswers: ['coisas associadas à noite', 'sensações que podem causar medo', 'falta de algo', 'estados calmos ou perturbadores', 'experiências dos sentidos'], thetaValue: 1.5),
      SimilarityItem(word1: 'tempo', word2: 'memória', level: AbstractionLevel.abstract, twoPointAnswers: ['estruturas que organizam a experiência do antes e do depois', 'elementos que constituem a identidade pessoal ao longo da vida', 'dimensões da existência que ligam o presente ao passado', 'conceitos filosóficos centrais para a compreensão do eu'], onePointAnswers: ['relacionados com o passado', 'coisas que não se podem tocar', 'temas filosóficos', 'algo que muda com a idade', 'conceitos abstratos'], thetaValue: 1.5),
      SimilarityItem(word1: 'lei', word2: 'moral', level: AbstractionLevel.abstract, twoPointAnswers: ['sistemas normativos que regulam o comportamento humano', 'conjuntos de regras que definem o que é permitido ou correto', 'estruturas que estabelecem obrigações e proibições', 'quadros de referência para julgar ações como certas ou erradas'], onePointAnswers: ['regras que as pessoas devem seguir', 'têm a ver com o que é certo e errado', 'conceitos ligados à ética', 'formas de controlo social', 'base da convivência em sociedade'], thetaValue: 1.5),
      SimilarityItem(word1: 'identidade', word2: 'pertença', level: AbstractionLevel.abstract, twoPointAnswers: ['dimensões psicossociais que definem o lugar do indivíduo no coletivo', 'conceitos que organizam a relação entre o eu e o grupo', 'construções que respondem às perguntas \'quem sou\' e \'onde me situo\'', 'fenómenos que articulam o individual com o social'], onePointAnswers: ['têm a ver com quem somos', 'relacionados com grupos e comunidades', 'sentimentos de ligação a algo', 'temas da psicologia', 'importantes para a autoestima'], thetaValue: 1.5),
      SimilarityItem(word1: 'razão', word2: 'intuição', level: AbstractionLevel.abstract, twoPointAnswers: ['faculdades cognitivas que guiam o julgamento e a decisão', 'modos de aceder ao conhecimento ou de chegar a conclusões', 'processos epistémicos distintos de orientar o pensamento', 'formas de orientar a ação perante a incerteza'], onePointAnswers: ['formas de pensar', 'capacidades da mente', 'temas da filosofia e da psicologia', 'maneiras de tomar decisões', 'relacionadas com a inteligência'], thetaValue: 1.5),
      SimilarityItem(word1: 'dever', word2: 'culpa', level: AbstractionLevel.abstract, twoPointAnswers: ['dimensões da consciência moral que regulam a conduta', 'estados psicológicos resultantes de normas interiorizadas', 'fenómenos da vida ética que ligam a ação à responsabilidade', 'conceitos que definem a relação do sujeito com as suas obrigações'], onePointAnswers: ['sentimentos relacionados com o que fazemos', 'conceitos da ética e da moral', 'têm a ver com responsabilidade', 'coisas que pesam na consciência', 'relacionados com o comportamento correto'], thetaValue: 1.5),
      SimilarityItem(word1: 'progresso', word2: 'decadência', level: AbstractionLevel.abstract, twoPointAnswers: ['processos de transformação direcional de sistemas ou civilizações', 'dinâmicas histórias opostas que descrevem a trajetória de sociedades', 'conceitos que exprimem o sentido de mudança ao longo do tempo', 'noções que avaliam a direção do desenvolvimento humano ou social'], onePointAnswers: ['estão relacionados com a mudança', 'formas de descrever a evolução da história', 'conceitos usados em sociologia e filosofia', 'têm a ver com o avanço ou o retrocesso', 'descrevem o estado de uma sociedade'], thetaValue: 1.5),
      SimilarityItem(word1: 'sacrifício', word2: 'renúncia', level: AbstractionLevel.abstract, twoPointAnswers: ['atos de abdicação voluntária em nome de um valor ou objetivo superior', 'formas de subordinar um bem imediato a um princípio mais elevado', 'gestos éticos que implicam prescindir de algo por uma causa', 'comportamentos que expressam a prevalência de um valor sobre um interesse pessoal'], onePointAnswers: ['implicam perder ou deixar algo', 'são atos difíceis de fazer', 'relacionados com a vontade e a escolha', 'vistos como virtudes em muitas culturas', 'associados à religião e à ética'], thetaValue: 1.5),
    ],
  ];
}
