/// Banque de paires du sous-test Similitudes — es (GÉNÉRÉ par IA, vérifié). 4 niveaux d'abstraction. NE PAS éditer à la main.
library;

import 'similarities_generator.dart';

List<List<SimilarityItem>> buildSpanishSimilarityBanks() {
  return [
    // concrete (12 paires)
    [
      SimilarityItem(word1: 'naranja', word2: 'plátano', level: AbstractionLevel.concrete, twoPointAnswers: ['son frutas', 'son un tipo de fruta', 'ambas son frutas', 'pertenecen al grupo de las frutas'], onePointAnswers: ['se comen', 'son alimentos', 'son dulces', 'tienen cáscara', 'son saludables', 'se venden en el mercado'], thetaValue: -1.5),
      SimilarityItem(word1: 'perro', word2: 'gato', level: AbstractionLevel.concrete, twoPointAnswers: ['son animales', 'son mascotas', 'son animales domésticos', 'ambos son animales de compañía'], onePointAnswers: ['tienen pelo', 'tienen cuatro patas', 'hacen ruido', 'viven en casa', 'comen pienso', 'necesitan cuidados'], thetaValue: -1.5),
      SimilarityItem(word1: 'silla', word2: 'sofá', level: AbstractionLevel.concrete, twoPointAnswers: ['son muebles', 'son asientos', 'sirven para sentarse', 'son un tipo de mobiliario'], onePointAnswers: ['están en casa', 'tienen patas', 'son de madera o tela', 'son cómodos', 'se usan en el salón', 'son objetos del hogar'], thetaValue: -1.5),
      SimilarityItem(word1: 'coche', word2: 'autobús', level: AbstractionLevel.concrete, twoPointAnswers: ['son vehículos', 'son medios de transporte', 'sirven para transportar personas', 'ambos son vehículos de motor'], onePointAnswers: ['tienen ruedas', 'van por la carretera', 'usan combustible', 'llevan gente de un sitio a otro', 'tienen motor', 'circulan por la calle'], thetaValue: -1.5),
      SimilarityItem(word1: 'camisa', word2: 'pantalón', level: AbstractionLevel.concrete, twoPointAnswers: ['son ropa', 'son prendas de vestir', 'son artículos de ropa', 'sirven para vestirse'], onePointAnswers: ['se llevan puestos', 'son de tela', 'se compran en una tienda de ropa', 'hay que lavarlos', 'cubren el cuerpo', 'los llevamos encima'], thetaValue: -1.5),
      SimilarityItem(word1: 'rosa', word2: 'clavel', level: AbstractionLevel.concrete, twoPointAnswers: ['son flores', 'son un tipo de flor', 'ambas son flores', 'pertenecen al grupo de las flores'], onePointAnswers: ['huelen bien', 'son bonitas', 'se regalan', 'se venden en la floristería', 'tienen pétalos', 'se ponen en un jarrón'], thetaValue: -1.5),
      SimilarityItem(word1: 'cuchillo', word2: 'tenedor', level: AbstractionLevel.concrete, twoPointAnswers: ['son cubiertos', 'son utensilios para comer', 'sirven para comer en la mesa', 'son instrumentos de mesa'], onePointAnswers: ['son de metal', 'se usan para comer', 'se ponen en la mesa', 'se lavan después de comer', 'se usan en las comidas', 'están en el cajón de la cocina'], thetaValue: -1.5),
      SimilarityItem(word1: 'guitarra', word2: 'violín', level: AbstractionLevel.concrete, twoPointAnswers: ['son instrumentos musicales', 'son instrumentos de cuerda', 'ambos son instrumentos de música', 'sirven para hacer música'], onePointAnswers: ['se tocan con las manos', 'suenan bien', 'se aprenden en una academia', 'hacen música', 'se usan en conciertos', 'son de madera'], thetaValue: -1.5),
      SimilarityItem(word1: 'zanahoria', word2: 'lechuga', level: AbstractionLevel.concrete, twoPointAnswers: ['son verduras', 'son vegetales', 'son hortalizas', 'ambas son verduras u hortalizas'], onePointAnswers: ['se comen', 'son alimentos saludables', 'se venden en la frutería o el mercado', 'sirven para cocinar', 'son de origen vegetal', 'se usan en ensaladas'], thetaValue: -1.5),
      SimilarityItem(word1: 'zapato', word2: 'bota', level: AbstractionLevel.concrete, twoPointAnswers: ['son calzado', 'son un tipo de calzado', 'sirven para calzarse', 'son prendas que se llevan en los pies'], onePointAnswers: ['se llevan en los pies', 'son de cuero o tela', 'se compran en una zapatería', 'los llevamos puestos', 'protegen los pies', 'van con los calcetines'], thetaValue: -1.5),
      SimilarityItem(word1: 'vaso', word2: 'taza', level: AbstractionLevel.concrete, twoPointAnswers: ['son recipientes para beber', 'sirven para beber', 'son utensilios para tomar líquidos', 'ambos sirven para beber'], onePointAnswers: ['son de cristal o cerámica', 'se usan en la cocina', 'se llenan de líquido', 'se lavan después de usarlos', 'se ponen en la mesa', 'caben en la mano'], thetaValue: -1.5),
      SimilarityItem(word1: 'lápiz', word2: 'bolígrafo', level: AbstractionLevel.concrete, twoPointAnswers: ['son utensilios para escribir', 'sirven para escribir', 'son instrumentos de escritura', 'ambos se usan para escribir o dibujar'], onePointAnswers: ['se cogen con la mano', 'se usan en el colegio', 'dejan marca en el papel', 'son alargados', 'se guardan en el estuche', 'sirven para hacer apuntes'], thetaValue: -1.5),
    ],
    // functional (14 paires)
    [
      SimilarityItem(word1: 'martillo', word2: 'destornillador', level: AbstractionLevel.functional, twoPointAnswers: ['herramientas', 'instrumentos para trabajos manuales', 'sirven para arreglar o montar cosas', 'utensilios de bricolaje'], onePointAnswers: ['se agarran con la mano', 'son de metal', 'tienen mango', 'se usan en obras o en casa'], thetaValue: -0.5),
      SimilarityItem(word1: 'barco', word2: 'avión', level: AbstractionLevel.functional, twoPointAnswers: ['medios de transporte', 'vehículos para viajar o trasladar mercancías', 'sirven para desplazarse de un lugar a otro', 'medios para transportar personas o carga'], onePointAnswers: ['son grandes', 'tienen motor', 'llevan pasajeros', 'son vehículos'], thetaValue: -0.5),
      SimilarityItem(word1: 'cuchillo', word2: 'tijeras', level: AbstractionLevel.functional, twoPointAnswers: ['utensilios de corte', 'herramientas para cortar', 'sirven para seccionar o separar materiales', 'instrumentos con filo'], onePointAnswers: ['son de metal', 'son afilados', 'pueden ser peligrosos', 'se usan en la cocina o en casa'], thetaValue: -0.5),
      SimilarityItem(word1: 'silla', word2: 'taburete', level: AbstractionLevel.functional, twoPointAnswers: ['muebles para sentarse', 'asientos', 'sirven para que las personas se sienten', 'mobiliario de descanso'], onePointAnswers: ['tienen patas', 'se usan en la cocina o en una barra', 'aguantan el peso de una persona', 'son muebles'], thetaValue: -0.5),
      SimilarityItem(word1: 'reloj', word2: 'calendario', level: AbstractionLevel.functional, twoPointAnswers: ['instrumentos para medir o registrar el tiempo', 'herramientas de organización temporal', 'sirven para saber qué hora o qué día es', 'dispositivos de control del tiempo'], onePointAnswers: ['tienen números', 'se usan a diario', 'se cuelgan en la pared o se llevan encima', 'son objetos cotidianos'], thetaValue: -0.5),
      SimilarityItem(word1: 'jabón', word2: 'champú', level: AbstractionLevel.functional, twoPointAnswers: ['productos de higiene personal', 'artículos para limpiar el cuerpo', 'sirven para la limpieza e higiene corporal', 'cosméticos de aseo'], onePointAnswers: ['hacen espuma', 'huelen bien', 'se usan en el baño', 'se aplican con agua'], thetaValue: -0.5),
      SimilarityItem(word1: 'paraguas', word2: 'chubasquero', level: AbstractionLevel.functional, twoPointAnswers: ['prendas o accesorios de protección contra la lluvia', 'sirven para protegerse del agua cuando llueve', 'artículos para resguardarse de la lluvia', 'elementos de protección frente a la lluvia'], onePointAnswers: ['se usan cuando llueve', 'se venden en tiendas', 'pueden ser de colores', 'los llevamos con mal tiempo'], thetaValue: -0.5),
      SimilarityItem(word1: 'gafas', word2: 'lupa', level: AbstractionLevel.functional, twoPointAnswers: ['instrumentos ópticos para mejorar la visión', 'dispositivos que ayudan a ver mejor', 'utensilios que usan lentes para corregir o ampliar la visión', 'herramientas ópticas'], onePointAnswers: ['tienen cristales', 'se usan con los ojos', 'ayudan a leer', 'son transparentes'], thetaValue: -0.5),
      SimilarityItem(word1: 'estufa', word2: 'chimenea', level: AbstractionLevel.functional, twoPointAnswers: ['aparatos o instalaciones para calentar el hogar', 'sistemas de calefacción doméstica', 'sirven para dar calor a una habitación', 'fuentes de calor en casa'], onePointAnswers: ['producen calor', 'se usan en invierno', 'están en el salón o el comedor', 'consumen combustible o energía'], thetaValue: -0.5),
      SimilarityItem(word1: 'cerradura', word2: 'candado', level: AbstractionLevel.functional, twoPointAnswers: ['mecanismos de seguridad para cerrar y proteger', 'dispositivos que impiden el acceso no autorizado', 'sirven para asegurar puertas u objetos', 'sistemas de cierre y protección'], onePointAnswers: ['se abren con llave', 'son de metal', 'protegen las pertenencias', 'se usan en puertas o cajas'], thetaValue: -0.5),
      SimilarityItem(word1: 'plancha', word2: 'secador', level: AbstractionLevel.functional, twoPointAnswers: ['electrodomésticos que usan calor para arreglar la ropa o el cabello', 'aparatos eléctricos de cuidado personal o del hogar', 'sirven para mejorar el aspecto de la ropa o el pelo', 'dispositivos que aplican calor para acondicionar'], onePointAnswers: ['usan electricidad', 'producen calor', 'se enchufan a la corriente', 'se usan en casa'], thetaValue: -0.5),
      SimilarityItem(word1: 'termómetro', word2: 'báscula', level: AbstractionLevel.functional, twoPointAnswers: ['instrumentos de medición corporal', 'aparatos para controlar la salud mediante mediciones del cuerpo', 'herramientas que miden parámetros físicos de las personas', 'dispositivos para vigilar la salud en casa o en la consulta'], onePointAnswers: ['los usa el médico', 'sirven para saber si alguien está bien de salud', 'muestran un valor numérico', 'se usan en casa o en la farmacia'], thetaValue: -0.5),
      SimilarityItem(word1: 'ascensor', word2: 'escalera', level: AbstractionLevel.functional, twoPointAnswers: ['medios para desplazarse verticalmente en un edificio', 'sistemas para acceder a distintas plantas', 'sirven para subir o bajar entre pisos', 'elementos de acceso vertical en edificios'], onePointAnswers: ['están en edificios', 'conectan plantas', 'los usan las personas a diario', 'son parte de la arquitectura de un edificio'], thetaValue: -0.5),
      SimilarityItem(word1: 'vela', word2: 'linterna', level: AbstractionLevel.functional, twoPointAnswers: ['fuentes de luz portátiles', 'dispositivos para iluminar cuando no hay luz eléctrica', 'sirven para alumbrar en la oscuridad', 'instrumentos de iluminación'], onePointAnswers: ['se usan cuando hay un apagón', 'producen luz', 'son pequeñas y manejables', 'las llevamos de acampada'], thetaValue: -0.5),
    ],
    // categorical (13 paires)
    [
      SimilarityItem(word1: 'violín', word2: 'trompeta', level: AbstractionLevel.categorical, twoPointAnswers: ['instrumentos musicales', 'instrumentos de música'], onePointAnswers: ['los dos producen sonido', 'los usan músicos', 'se aprenden con práctica', 'pueden tocarse en conciertos'], thetaValue: 0.5),
      SimilarityItem(word1: 'rabia', word2: 'alegría', level: AbstractionLevel.categorical, twoPointAnswers: ['emociones', 'sentimientos'], onePointAnswers: ['las dos se sienten por dentro', 'pueden verse en la expresión de la cara', 'afectan al comportamiento', 'son reacciones ante algo que ocurre'], thetaValue: 0.5),
      SimilarityItem(word1: 'roble', word2: 'pino', level: AbstractionLevel.categorical, twoPointAnswers: ['árboles', 'tipos de árbol'], onePointAnswers: ['los dos tienen tronco y ramas', 'producen madera', 'crecen en bosques', 'son plantas de gran tamaño'], thetaValue: 0.5),
      SimilarityItem(word1: 'tiburón', word2: 'salmón', level: AbstractionLevel.categorical, twoPointAnswers: ['peces', 'animales acuáticos con aletas'], onePointAnswers: ['los dos nadan', 'tienen escamas', 'se reproducen poniendo huevos', 'son presas de pesca'], thetaValue: 0.5),
      SimilarityItem(word1: 'cobre', word2: 'hierro', level: AbstractionLevel.categorical, twoPointAnswers: ['metales', 'materiales metálicos'], onePointAnswers: ['los dos se extraen de la tierra', 'se usan en la industria y la construcción', 'son duros y resistentes', 'pueden fundirse con calor'], thetaValue: 0.5),
      SimilarityItem(word1: 'novela', word2: 'poema', level: AbstractionLevel.categorical, twoPointAnswers: ['obras literarias', 'géneros de la literatura'], onePointAnswers: ['los dos están escritos por un autor', 'pueden transmitir emociones', 'se publican en libros', 'tienen un estilo propio'], thetaValue: 0.5),
      SimilarityItem(word1: 'abogado', word2: 'juez', level: AbstractionLevel.categorical, twoPointAnswers: ['profesionales del derecho', 'juristas'], onePointAnswers: ['los dos trabajan en el ámbito judicial', 'conocen la ley', 'tienen una carrera universitaria', 'intervienen en los tribunales'], thetaValue: 0.5),
      SimilarityItem(word1: 'pintura', word2: 'escultura', level: AbstractionLevel.categorical, twoPointAnswers: ['obras de arte', 'formas de arte plástico'], onePointAnswers: ['las dos las crean artistas', 'se exponen en museos', 'requieren creatividad y técnica', 'pueden representar personas o paisajes'], thetaValue: 0.5),
      SimilarityItem(word1: 'trigo', word2: 'arroz', level: AbstractionLevel.categorical, twoPointAnswers: ['cereales', 'cultivos de cereal'], onePointAnswers: ['los dos son alimentos básicos', 'se cultivan en el campo', 'se usan para hacer comida', 'son fuente de hidratos de carbono'], thetaValue: 0.5),
      SimilarityItem(word1: 'diabetes', word2: 'asma', level: AbstractionLevel.categorical, twoPointAnswers: ['enfermedades crónicas', 'trastornos de salud que requieren tratamiento continuo'], onePointAnswers: ['las dos afectan la calidad de vida', 'se controlan con medicación', 'las diagnostica un médico', 'pueden aparecer desde la infancia'], thetaValue: 0.5),
      SimilarityItem(word1: 'envidia', word2: 'orgullo', level: AbstractionLevel.categorical, twoPointAnswers: ['emociones relacionadas con la autovaloración', 'sentimientos que nacen de compararse con los demás'], onePointAnswers: ['los dos pueden afectar las relaciones sociales', 'son actitudes que se sienten internamente', 'pueden influir en el comportamiento', 'se consideran vicios en la tradición española'], thetaValue: 0.5),
      SimilarityItem(word1: 'pistola', word2: 'espada', level: AbstractionLevel.categorical, twoPointAnswers: ['armas', 'instrumentos diseñados para el combate'], onePointAnswers: ['las dos pueden causar heridas', 'se han usado en conflictos bélicos', 'requieren entrenamiento para usarse', 'son peligrosas'], thetaValue: 0.5),
      SimilarityItem(word1: 'microscopio', word2: 'telescopio', level: AbstractionLevel.categorical, twoPointAnswers: ['instrumentos ópticos de observación científica', 'aparatos que amplían la visión más allá de lo perceptible a simple vista'], onePointAnswers: ['los dos usan lentes', 'se emplean en investigación científica', 'ayudan a ver con más detalle', 'requieren luz para funcionar'], thetaValue: 0.5),
    ],
    // abstract (12 paires)
    [
      SimilarityItem(word1: 'libertad', word2: 'justicia', level: AbstractionLevel.abstract, twoPointAnswers: ['valores o ideales abstractos que fundamentan la convivencia en sociedad', 'principios filosóficos y morales que rigen el orden social', 'ideales normativos que orientan la organización de una comunidad'], onePointAnswers: ['conceptos que defiende la democracia', 'palabras que aparecen en las constituciones', 'cosas por las que luchan las personas'], thetaValue: 1.5),
      SimilarityItem(word1: 'alabanza', word2: 'castigo', level: AbstractionLevel.abstract, twoPointAnswers: ['mecanismos de regulación o influencia del comportamiento', 'instrumentos de control social o educativo que moldean la conducta', 'herramientas de refuerzo y corrección del comportamiento ajeno'], onePointAnswers: ['reacciones ante las acciones de alguien', 'consecuencias de los actos', 'cosas que reciben los niños según su comportamiento'], thetaValue: 1.5),
      SimilarityItem(word1: 'fe', word2: 'esperanza', level: AbstractionLevel.abstract, twoPointAnswers: ['virtudes o disposiciones internas que sostienen al ser humano ante la incertidumbre', 'actitudes subjetivas orientadas hacia algo positivo que da sentido a la existencia', 'estados de la voluntad que permiten afrontar lo que escapa al control humano'], onePointAnswers: ['sentimientos positivos', 'cosas relacionadas con la religión', 'formas de afrontar las dificultades'], thetaValue: 1.5),
      SimilarityItem(word1: 'azar', word2: 'destino', level: AbstractionLevel.abstract, twoPointAnswers: ['concepciones filosóficas sobre lo que determina el curso de los acontecimientos', 'principios explicativos de lo que escapa al control y la previsión humana', 'marcos de interpretación de la causalidad en la vida de las personas'], onePointAnswers: ['factores que explican lo que nos sucede', 'conceptos que la gente usa para hablar de la suerte', 'ideas relacionadas con el futuro incierto'], thetaValue: 1.5),
      SimilarityItem(word1: 'orgullo', word2: 'vergüenza', level: AbstractionLevel.abstract, twoPointAnswers: ['emociones autoevaluativas vinculadas a la identidad moral y el juicio sobre uno mismo', 'sentimientos que emergen de la valoración de la propia conducta ante las normas sociales', 'respuestas afectivas a la adecuación o transgresión de valores internalizados'], onePointAnswers: ['sentimientos intensos sobre uno mismo', 'emociones relacionadas con lo que los demás piensan de nosotros', 'reacciones ante los propios actos'], thetaValue: 1.5),
      SimilarityItem(word1: 'verdad', word2: 'belleza', level: AbstractionLevel.abstract, twoPointAnswers: ['valores o ideales trascendentes que la humanidad persigue a través del conocimiento y el arte', 'fines absolutos que orientan la búsqueda filosófica y estética del ser humano', 'nociones que definen aspiraciones superiores de la razón y la sensibilidad'], onePointAnswers: ['cosas positivas que todo el mundo valora', 'conceptos que estudia la filosofía', 'ideales que inspiran a las personas'], thetaValue: 1.5),
      SimilarityItem(word1: 'poder', word2: 'responsabilidad', level: AbstractionLevel.abstract, twoPointAnswers: ['dimensiones inseparables del ejercicio de la autoridad o el liderazgo', 'principios éticos y políticos que articulan la relación entre capacidad de actuar y rendir cuentas', 'nociones que definen las condiciones legítimas del gobierno sobre los demás'], onePointAnswers: ['cosas relacionadas con los cargos de importancia', 'conceptos del ámbito político o empresarial', 'ideas sobre cómo debe actuar quien tiene influencia'], thetaValue: 1.5),
      SimilarityItem(word1: 'memoria', word2: 'identidad', level: AbstractionLevel.abstract, twoPointAnswers: ['constructos psicológicos interdependientes que configuran el sentido del yo a lo largo del tiempo', 'nociones que definen la continuidad y coherencia de una persona o colectividad', 'procesos que dan consistencia al sujeto y le permiten reconocerse como el mismo ser'], onePointAnswers: ['conceptos importantes en psicología', 'cosas que nos hacen ser quienes somos', 'elementos que diferencian a unas personas de otras'], thetaValue: 1.5),
      SimilarityItem(word1: 'voluntad', word2: 'razón', level: AbstractionLevel.abstract, twoPointAnswers: ['facultades superiores del ser humano que orientan su conducta y su pensamiento', 'capacidades internas que definen la condición racional y moral de la persona', 'potencias del espíritu humano que fundamentan la autonomía y la acción libre'], onePointAnswers: ['cosas que necesitamos para tomar decisiones', 'conceptos de filosofía sobre la mente', 'cualidades internas que nos distinguen de los animales'], thetaValue: 1.5),
      SimilarityItem(word1: 'dignidad', word2: 'honor', level: AbstractionLevel.abstract, twoPointAnswers: ['valores morales que definen el reconocimiento y el respeto que merece una persona', 'principios éticos que fundamentan la autoestima y la consideración social del individuo', 'nociones que articulan el valor intrínseco y la reputación de un ser humano'], onePointAnswers: ['cosas importantes para la autoestima', 'valores que se relacionan con el respeto', 'conceptos que definen cómo se trata a las personas'], thetaValue: 1.5),
      SimilarityItem(word1: 'deber', word2: 'derecho', level: AbstractionLevel.abstract, twoPointAnswers: ['categorías normativas complementarias que estructuran la vida moral y jurídica de los individuos', 'principios que regulan las obligaciones y las prerrogativas del ser humano en sociedad', 'nociones éticas y jurídicas que articulan la relación entre el individuo y la comunidad'], onePointAnswers: ['conceptos del ámbito del derecho y la moral', 'cosas que tenemos o que estamos obligados a hacer', 'términos que aparecen en textos legales o filosóficos'], thetaValue: 1.5),
      SimilarityItem(word1: 'conciencia', word2: 'culpa', level: AbstractionLevel.abstract, twoPointAnswers: ['fenómenos psicológicos internos que regulan el comportamiento moral del individuo', 'experiencias subjetivas vinculadas al juicio ético sobre los propios actos', 'procesos de autoevaluación moral que orientan y sancionan la conducta desde dentro'], onePointAnswers: ['cosas relacionadas con saber si uno ha actuado bien o mal', 'sensaciones internas asociadas a los propios errores', 'conceptos de la psicología y la ética'], thetaValue: 1.5),
    ],
  ];
}
